[tool.poetry]
name = "chef"
version = "0.1.0"
description = "A Python package by Cheffelo."
authors = ["Your full name <Your email address>"]
packages = [{include = "chef"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
ruff = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chef = 'chef.cli:cli'
