[tool.poetry]
name = "chef"
version = "0.1.0"
description = "A simple CLI tool for creating and managing projects and packages in Cheffelo's monorepo."
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [
    { include = "chef" },
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.7"
cookiecutter = "^2.5.0"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
ruff = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chef = 'chef.cli:cli'
