[tool.poetry]
name = "chef"
version = "0.2.0"
description = "A simple CLI tool for creating and managing projects and packages in Cheffelo's monorepo."
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [
    { include = "chef" },
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
cookiecutter = "2.5.0"
project-owners = {path = "../../packages/project-owners", develop = true}
pydantic-settings = "^2.1.0"
pytest-mock = "^3.14.0"
azure-identity = "^1.23.0"
azure-mgmt-appcontainers = "^3.2.0"
azure-mgmt-resource = "^24.0.0"
key-vault = {path = "../../packages/key-vault", develop = true}

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
ruff = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chef = 'chef.cli:cli'
