FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

# install Poetry
RUN pip install --no-cache-dir poetry=='1.8.2'

# Installing utils deps
RUN apt-get update && \
    apt-get install --no-install-recommends -y g++ make libc6-dev unixodbc-dev libpq-dev curl gnupg2

# Install Microsoft ODBC driver for SQL Server
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc && \
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev


# set the home directory
ENV APP_HOME=/workspaces/sous-chef
ENV SERVICE_HOME=$APP_HOME/projects/preselector

# copy source code
WORKDIR $APP_HOME
COPY packages packages

WORKDIR $SERVICE_HOME
RUN mkdir -p preselector && touch preselector/__init__.py

COPY projects/preselector/pyproject.toml .
COPY projects/preselector/poetry.lock .

# install requirements
ARG DEP_GROUP
RUN poetry config virtualenvs.create false
RUN poetry install ${DEP_GROUP} -n && rm -rf ~/.cache/pypoetry/cache

# copy source code
COPY projects/preselector .

# store the git branch and commit hash as env variables
ARG GIT_BRANCH
ARG GIT_COMMIT_HASH
ENV GIT_BRANCH=${GIT_BRANCH}
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

# set starting command
WORKDIR $SERVICE_HOME
CMD python preselector/main.py

ENV TAG=$TAG
