table 'Order Status'
	lineageTag: 1328111a-5f01-4b3f-8a2c-c02c4dad327c

	column pk_dim_order_status
		dataType: string
		isHidden
		lineageTag: f64c065b-32a3-4a2a-a6e8-351923007ba8
		summarizeBy: none
		sourceColumn: pk_dim_order_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_status_id
		dataType: string
		isHidden
		lineageTag: effcc23c-12dd-4d4a-b398-a1b4cbea71cd
		summarizeBy: none
		sourceColumn: order_status_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Status Name'
		dataType: string
		lineageTag: 8fbab1fb-dc08-4292-b902-71c8c29cf93c
		summarizeBy: none
		sourceColumn: Order Status Name

		annotation SummarizationSetBy = Automatic

	column 'Can be Cancelled'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4ca3ee74-95aa-4585-a202-a21d279d0c52
		summarizeBy: none
		sourceColumn: Can be Cancelled

		annotation SummarizationSetBy = Automatic

	partition 'Order Status' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name="gold",Kind="Schema"]}[Data],
				    dim_order_status_Table = gold_Schema{[Name="dim_order_status",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dim_order_status_Table,{{"order_status_name", "Order Status Name"}, {"can_be_cancelled", "Can be Cancelled"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

