table 'Order Measures'
	lineageTag: 6c298811-8ad5-482b-b89a-827db89210a3

	measure 'Sum Total Amount Ex Vat' = SUM('Order Measures'[total_amount_ex_vat])
		lineageTag: 9514c3b0-8d1c-49a4-a547-99ac13fa089d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum Total Amount Inc Vat' = SUM('Order Measures'[total_amount_inc_vat])
		lineageTag: 5cba6729-7b7c-48ce-9c67-e695bff2c63a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Orders' = DISTINCTCOUNTNOBLANK('Order Measures'[cms_order_id])
		lineageTag: 3fe674e5-e11d-4968-b77f-38e87d1f983e

	measure 'Number of Orders + 1' = DISTINCTCOUNTNOBLANK('Order Measures'[cms_order_id]) + 1
		lineageTag: 6e3daed4-ee40-4f07-8aea-7b3a1c3772c5

	measure 'Average Total Amount Ex Vat' = DIVIDE([Sum Total Amount Ex Vat],[Number of Orders],BLANK())
		lineageTag: 85357b8f-6a82-4a0a-8243-d2756573a1b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Total Amount Inc Vat' = DIVIDE([Sum Total Amount Inc Vat],[Number of Orders],BLANK())
		lineageTag: e35a4577-2ae2-46b4-8511-031e29d678ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Orders with Recipe Leaflet' = CALCULATE([Number of Orders], 'Order Measures'[has_recipe_leaflets] = TRUE())
		formatString: 0
		lineageTag: cf598a2d-2b0e-4370-959f-3d0dab5bbcec

	measure 'Sum Variation Quantity' = SUM('Order Measures'[variation_qty])
		formatString: 0
		lineageTag: 6da36c65-3977-4355-9613-98ce2076a5ba

	measure 'Average Unit Price Inc Vat' = DIVIDE([Sum Total Amount Inc Vat],[Sum Variation Quantity])
		lineageTag: 01e8c74d-66dd-4082-bcee-a4c91dcc5c76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Unit Price Ex Vat' = DIVIDE([Sum Total Amount Ex Vat],[Sum Variation Quantity])
		lineageTag: 461d3a40-d20c-45d2-aa78-46a36a2ce6ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pk_fact_order_line
		dataType: string
		isHidden
		lineageTag: 43c6d97d-3a61-4988-8dff-61961db660f6
		summarizeBy: none
		sourceColumn: pk_fact_order_line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ops_order_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1f406b18-f485-49a4-afc6-a0b176b86f77
		summarizeBy: sum
		sourceColumn: ops_order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_status_id
		dataType: string
		isHidden
		lineageTag: 97d4bcb3-e53a-4277-af57-57a94757ec39
		summarizeBy: none
		sourceColumn: order_status_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_type_id
		dataType: string
		isHidden
		lineageTag: 094f462a-d367-48ec-9a45-4eeba1a9b353
		summarizeBy: none
		sourceColumn: order_type_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_line_id
		dataType: string
		isHidden
		lineageTag: 0319b8db-e0ea-4266-98d5-4460f2f2825a
		summarizeBy: none
		sourceColumn: order_line_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column agreement_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7b71a3a7-cf5c-4b49-986c-49c4bd9b7042
		summarizeBy: sum
		sourceColumn: agreement_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_variation_id
		dataType: string
		isHidden
		lineageTag: 64dfca24-3043-4e81-a204-f255f0399874
		summarizeBy: none
		sourceColumn: product_variation_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_line_type_name
		dataType: string
		isHidden
		lineageTag: 6093c33b-13e6-4718-84fa-0caeafa121df
		summarizeBy: none
		sourceColumn: order_line_type_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column variation_qty
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8a862b85-78e8-4834-b545-2d66d294729d
		summarizeBy: sum
		sourceColumn: variation_qty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column vat
		dataType: double
		isHidden
		lineageTag: 4521f41d-a9a8-484a-9159-d4046240c6ea
		summarizeBy: sum
		sourceColumn: vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_price_ex_vat
		dataType: double
		isHidden
		lineageTag: 7f9d2ac1-3639-4135-b1dd-80415012e217
		summarizeBy: sum
		sourceColumn: unit_price_ex_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_price_inc_vat
		dataType: double
		isHidden
		lineageTag: 97dc1a98-b450-4c70-b648-52f8b8697a06
		summarizeBy: sum
		sourceColumn: unit_price_inc_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_amount_ex_vat
		dataType: double
		isHidden
		lineageTag: 08f563d8-4a6b-42f1-a6a2-defc5b017a7f
		summarizeBy: sum
		sourceColumn: total_amount_ex_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_amount_inc_vat
		dataType: double
		isHidden
		lineageTag: 7d29bced-8264-4b7b-ad97-48e24fed616a
		summarizeBy: sum
		sourceColumn: total_amount_inc_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_delivery
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61ef0da3-7497-4720-a9b7-cc7bffba031a
		summarizeBy: none
		sourceColumn: has_delivery

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column has_recipe_leaflets
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ae54f7b9-96c6-45c6-8350-728a3cb4e046
		summarizeBy: none
		sourceColumn: has_recipe_leaflets

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delivery_week_monday_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 62dff093-e3e8-4176-8b77-39772f786b2f
		summarizeBy: none
		sourceColumn: delivery_week_monday_date

		variation Variation
			isDefault
			relationship: dcd30575-0293-4c7c-85da-8aac8d173550
			defaultHierarchy: LocalDateTable_20903e7e-c150-4dec-9751-1b987018c94d.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_created_at
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: dfd7bb10-1ed7-44e4-ada5-a659e860ef99
		summarizeBy: none
		sourceColumn: order_created_at

		variation Variation
			isDefault
			relationship: 171c2137-a01f-4390-a89d-492a37e62d06
			defaultHierarchy: LocalDateTable_788da4b2-62fb-4f34-96ce-6a72bf4ace3b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_order_types
		dataType: string
		isHidden
		lineageTag: 5433926e-8415-406d-bcf6-50d345c90dc2
		summarizeBy: none
		sourceColumn: fk_dim_order_types

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_order_status
		dataType: string
		isHidden
		lineageTag: 560c4672-6c80-43a1-8a94-77df58054260
		summarizeBy: none
		sourceColumn: fk_dim_order_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_products
		dataType: string
		isHidden
		lineageTag: 272a1795-5763-4cfd-9ac3-330f7a344bf8
		summarizeBy: none
		sourceColumn: fk_dim_products

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_billing_agreements
		dataType: string
		isHidden
		lineageTag: 0becfd8d-060a-46cc-8f99-831e7bb3c105
		summarizeBy: none
		sourceColumn: fk_dim_billing_agreements

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_companies
		dataType: string
		isHidden
		lineageTag: 791ace8d-5c19-4331-ae91-56c97085cfc2
		summarizeBy: none
		sourceColumn: fk_dim_companies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_date
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3f4a1497-0525-4d8c-8938-ad437ac4ef2c
		summarizeBy: none
		sourceColumn: fk_dim_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cms_order_id
		dataType: string
		isHidden
		lineageTag: 70d325d5-6b5b-4424-b033-e2139b7ba9d6
		summarizeBy: none
		sourceColumn: cms_order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Order Measures' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name="gold",Kind="Schema"]}[Data],
				    fact_orders_Table = gold_Schema{[Name="fact_orders",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(fact_orders_Table, each [order_created_at] >= RangeStart and [order_created_at] < RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

