
# This file defines dbt profiles for deployed dbt jobs.
transform:
   target: dev # default target
   outputs:
    # The default target when deployed with the Databricks CLI
    # N.B. when you use dbt from the command line, it uses the profile from .dbt/profiles.yml
    dev:
      type: databricks
      method: http
      catalog: dev
      schema: dev
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      token: "{{ env_var('DATABRICKS_DBT_TOKEN') }}"
    
    # Used for the CI pipeline
    ci:
      type: databricks
      method: http
      catalog: dev
      schema: ci

      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      token: "{{ env_var('DATABRICKS_DBT_TOKEN') }}"

    # The test target when deployed with the Databricks CLI
    test:
      type: databricks
      method: http
      catalog: test
      schema: test
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      token: "{{ env_var('DATABRICKS_DBT_TOKEN') }}"


    # The production target when deployed with the Databricks CLI
    prod:
      type: databricks
      method: http
      catalog: prod
      schema: prod
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      token: "{{ env_var('DATABRICKS_DBT_TOKEN') }}"
