[tool.poetry]
name = "ml_contract_helper"
version = "0.1.0"
description = "A Python package by Cheffelo."
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [{include = "ml_contract_helper"}]

[tool.poetry.dependencies]
python = "^3.10"
data-contracts = {path = "../../packages/data-contracts", develop = true}
scikit-learn = "^1.7.1"
numpy = "1.26.4"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
pyright = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
