# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell

- repo: local
  hooks:
  - id: ruff format
    name: "Ruff Format"
    language: system
    types: [python]
    entry: ruff format

  - id: ruff lint
    name: "Ruff Lint"
    language: system
    types: [python]
    entry: ruff check --fix

  - id: typecheck
    name: "Pyright Type Checking"
    language: system
    types: [python]
    entry: pyright
