def get_recipe_numeric_features_config(company_code: str) -> list[str]:
    """
    The model requires numerical features
    which are generated by normalization and one hot encoding
    However, the exact columns are different for each company
    These features will be used for both the training and predict step,
    hence as a shared_config
    """
    non_one_hot_features = [
        "cooking_time_mean",
        "number_of_recipe_steps",
        "number_of_taxonomies",
        "number_of_ingredients",
        "has_vegetarian_taxonomy",
        "has_quick_and_easy_taxonomy",
        "has_low_calorie_taxonomy",
    ]
    if company_code == "AMK":
        one_hot_features = [
            "recipe_main_ingredient_name_english_Beef",
            "recipe_main_ingredient_name_english_Fish",
            "recipe_main_ingredient_name_english_Game",
            "recipe_main_ingredient_name_english_Lamb",
            "recipe_main_ingredient_name_english_Pork",
            "recipe_main_ingredient_name_english_Poultry",
            "recipe_main_ingredient_name_english_Shellfish",
            "recipe_main_ingredient_name_english_Vegan",
            "recipe_main_ingredient_name_english_Vegetarian",
        ]
    elif company_code == "GL":
        one_hot_features = [
            "recipe_main_ingredient_name_english_Beef",
            "recipe_main_ingredient_name_english_Fish",
            "recipe_main_ingredient_name_english_Game",
            "recipe_main_ingredient_name_english_Lamb",
            "recipe_main_ingredient_name_english_Pork",
            "recipe_main_ingredient_name_english_Poultry",
            "recipe_main_ingredient_name_english_Shellfish",
            "recipe_main_ingredient_name_english_Vegetarian",
        ]
    elif company_code == "LMK":
        one_hot_features = [
            "recipe_main_ingredient_name_english_Beef",
            "recipe_main_ingredient_name_english_Fish",
            "recipe_main_ingredient_name_english_Game",
            "recipe_main_ingredient_name_english_Pork",
            "recipe_main_ingredient_name_english_Poultry",
            "recipe_main_ingredient_name_english_Shellfish",
            "recipe_main_ingredient_name_english_Vegan",
            "recipe_main_ingredient_name_english_Vegetarian",
        ]
    elif company_code == "RT":
        one_hot_features = [
            "recipe_main_ingredient_name_english_Beef",
            "recipe_main_ingredient_name_english_Fish",
            "recipe_main_ingredient_name_english_Pork",
            "recipe_main_ingredient_name_english_Poultry",
            "recipe_main_ingredient_name_english_Shellfish",
            "recipe_main_ingredient_name_english_Vegetarian",
        ]

    else:
        raise ValueError(f"Company code {company_code} not supported")
    recipe_numeric_features = non_one_hot_features + one_hot_features
    return recipe_numeric_features
