# yaml-language-server: $schema=../../bundle_config_schema.json
resources:
  jobs:
    order_forecasting_train_gl:
      name: orders-forecasting-train-gl-${bundle.target}

      job_clusters:
        - job_cluster_key: orders-forecasting
          new_cluster:
            num_workers: 1
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_DS3_v2
            custom_tags:
              user: "Data scientists"
              tool: "Orders forecasting"
              env: ${bundle.target}
              managed_by: "manually"
            docker_image:
              url: "${var.docker_image_url}"
              basic_auth:
                username: "{{secrets/auth_common/docker-registry-username}}"
                password: "{{secrets/auth_common/docker-registry-password}}"

      schedule:
        quartz_cron_expression: '0 30 02 ? * THU'
        timezone_id: UTC
        pause_status: PAUSED # UNPAUSED

      email_notifications:
        on_failure:
          - thomas.sve@cheffelo.com
        on_success:
          - thomas.sve@cheffelo.com

      tasks:
        - task_key: OrderForecastingGenerateFeatures
          job_cluster_key: orders-forecasting
          notebook_task:
            notebook_path: ../../generate_features.py
        - task_key: OrderForecastingTrain
          job_cluster_key: orders-forecasting
          notebook_task:
            notebook_path: ../../train.py
          depends_on:
            - task_key: OrderForecastingGenerateFeatures
        - task_key: OrderForecastingPredict
          job_cluster_key: orders-forecasting
          notebook_task:
            notebook_path: ../../predict.py
          depends_on:
            - task_key: OrderForecastingTrain
        - task_key: OrderForecastingEvaluatePredictions
          job_cluster_key: orders-forecasting
          notebook_task:
            notebook_path: ../../evaluate.py
          depends_on:
            - task_key: OrderForecastingPredict
      parameters:
        - name: company
          default: "GL"
        - name: env
          default: "dev"
        - name: target
          default: "all"
        - name: num_weeks
          default: "11"
