resources:
  jobs:
    dishes-forecasting-train-sweden:
      name: dishes-forecasting-train-sweden-${bundle.target}
      permissions:
        - group_name: data-scientists
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: dishes-forecasting-train-sweden
          new_cluster:
            num_workers: 1
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_DS4_v2
            custom_tags:
              user: "Data scientists"
              tool: "Dishes forecasting"
              env: ${bundle.target}
              managed_by: "manually"
            docker_image:
              url: "${var.docker_image_url}"
              basic_auth:
                username: "{{secrets/auth_common/docker-registry-username}}"
                password: "{{secrets/auth_common/docker-registry-password}}"

      email_notifications:
        on_failure:
          - sylvia.liu@cheffelo.com

      tasks:
        - task_key: train-dishes-forecasting-sweden-lmk
          job_cluster_key: dishes-forecasting-train-sweden
          notebook_task:
            notebook_path: ../1_model_train.py
            base_parameters:
              env: "${var.environment}"
              company: LMK
        - task_key: slack-notification-success-lmk
          depends_on:
            - task_key: train-dishes-forecasting-sweden-lmk
          run_if: ALL_SUCCESS
          run_job_task:
            job_id: ${var.slack_notification_job_id} #Reads from the variable defined in the databricks.yml file
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              body_message: ✅ Dishes forecasting training step for LMK finished!
              is_error: false
        - task_key: slack-notification-failied-lmk
          depends_on:
            - task_key: train-dishes-forecasting-sweden-lmk
          run_if: ALL_FAILED
          run_job_task:
            job_id: ${var.slack_notification_job_id} #Reads from the variable defined in the databricks.yml file
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              header_message: ❌ Dishes forecasting training step for LMK failed!
              body_message: Check databricks for details...
              is_error: true
              relevant_people: sylvia
