[tool.poetry]
name = "data_contracts"
version = "0.1.0"
description = "A set of data contracts that ML project expect to be upheld"
authors = ["Mats E. Mollestad <mats.mollestad@cheffelo.com>"]
packages = [{include = "data_contracts"}]

[tool.poetry.dependencies]
python = "^3.10"
aligned = { version="^0.0.108", extras=["azure", "pandas"]}
azure-storage-blob = "^12.19.0"
azure-identity = "^1.15.0"
pyarrow = "^14.0.0"
pyodbc = {version = "4.0.35", optional = true }
aioodbc = {version = "0.4.1", optional = true }
project-owners = {path = "../../packages/project-owners", develop = true}
deltalake = "^0.16.2"
openai = "^1.30.5"
numpy = "1.26.4"

[tool.poetry.extras]
mssql = ["pyodbc", "aioodbc"]

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}
pyright = "^1.1.376"

[tool.pyright]
exclude = ["data_contracts/sql_server.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
