GL: &default
  train_start_yyyyww: 202301 #202101
  train_end_yyyyww: 202409
  feature_lookups:
    - weekly_dishes_features:
        features_container: mlfeaturetesting
        columns:
          primary_keys:
            - year
            - week
            - company_id
            - variation_id
          feature_columns:
            - recipe_portion_id
            - flex_menu_recipe_order
            - is_default
            - num_recipe_rating
            - average_recipe_rating
    - recipe_features:
        features_container: mlfeaturetesting
        columns:
          primary_keys:
            - recipe_portion_id
          feature_columns:
            - cooking_time_from
            - cooking_time_to
            - number_of_recipe_steps
            - agurk
            - aioli
            - aluminiumsfolie
            - appelsin
            - aromasopp
            - asparges
            - avokado
            - bacon
            - baconterninger
            - bagetter
            - bakepapir
            - balsamicovinaigrette
            - barbecuesaus
            - basilikum
            - basmatiris
            - bbq
            - bearn
            - bechamelsaus
            - bladpersille
            - blank
            - blomkål
            - blåbærsyltetøy
            - bolognese
            - brokkoli
            - brun
            - bulgur
            - bønner
            - carne
            - che
            - cherrytomater
            - chili
            - chiliflak
            - chilimajones
            - chipotlemiks
            - choy
            - con
            - cr
            - crispy
            - curry
            - dill
            - dippsaus
            - eddik
            - egg
            - eggenudler
            - eple
            - eplesider
            - ertepur
            - erter
            - ertestuing
            - fersk
            - fetaost
            - filetstykke
            - finkuttet
            - finsnittet
            - fiskeboller
            - fiskegrateng
            - fiskekaker
            - friske
            - fullkornsris
            - garam
            - grana
            - grande
            - gressløk
            - grillet
            - grove
            - grønn
            - grønne
            - grønnkål
            - grønnsaker
            - grønnsaksbuljong
            - grønt
            - guacamole
            - gul
            - gulrot
            - gulrøtter
            - gyroskjøtt
            - hakkede
            - hamburgerbrød
            - hjemmelaget
            - hjertesalat
            - hoisinsaus
            - honning
            - hvetemel
            - hvit
            - hvitløk
            - hvitløksdressing
            - hvitløksfedd
            - hvitvins
            - hvitvinseddik
            - hønsebuljong
            - ingefær
            - ingefærsaus
            - jasminris
            - karbonader
            - karri
            - kikerter
            - kinesisk
            - kjerneblanding
            - kjøttdeig
            - kokoskrem
            - kokosmelk
            - kokte
            - koriander
            - kremet
            - krydder
            - kryddermiks
            - kryddersmør
            - kylling
            - kyllingbryst
            - kyllingfilet
            - kyllingkjøttdeig
            - kyllinglår
            - kålrot
            - kålsalat
            - laks
            - laksefilet
            - lett
            - lettrømme
            - lime
            - linguine
            - linser
            - løk
            - mager
            - mais
            - maisstivelse
            - mango
            - mangochutney
            - mangodressing
            - margarin
            - masala
            - melk
            - mexican
            - mozzarella
            - multibrød
            - naturell
            - oksebuljong
            - olivenolje
            - olje
            - oregano
            - ost
            - ovnsbakt
            - ovnsbakte
            - padano
            - pak
            - panering
            - panert
            - pannekaker
            - pannestekt
            - paprika
            - paprikakrydder
            - pasta
            - peanøtter
            - pepper
            - pepperoni
            - persillade
            - pizza
            - pizzabunner
            - pizzasaus
            - pork
            - poteter
            - potetkrydder
            - potetmos
            - premium
            - pulled
            - purre
            - reddiker
            - reker
            - remulade
            - restaurantsalat
            - revet
            - ris
            - ruccola
            - rustikk
            - rustikke
            - råkost
            - råkostmiks
            - rød
            - rødkål
            - rødløk
            - rødvins
            - røkt
            - rømme
            - rørte
            - salat
            - salsa
            - salsicciadeig
            - salt
            - saus
            - sellerirot
            - sennep
            - sennepsvinaigrette
            - sesamfrø
            - sitron
            - sitruskrydder
            - sjalottløk
            - sjampinjong
            - skinn
            - skiver
            - skivet
            - sløyfes
            - småpoteter
            - smør
            - sopp
            - soppsaus
            - sous
            - soya
            - soyasaus
            - spice
            - spicy
            - spinat
            - sprø
            - squash
            - srirachasaus
            - ssaus
            - stekt
            - strimlet
            - sukker
            - svart
            - svarte
            - svin
            - svinekam
            - svinestrimler
            - sweet
            - syltet
            - søtpotet
            - søtpoteter
            - teriyakisaus
            - three
            - timian
            - tobladssalat
            - tomat
            - tomater
            - tomatpur
            - tomatsalat
            - tomatsalsa
            - torsk
            - torskefilet
            - tortillachips
            - tortillalefser
            - tyrkisk
            - tyttebær
            - tzatziki
            - urtedressing
            - urtemiks
            - utbenet
            - vann
            - vide
            - vårløk
            - wok
            - yoghurt
            - tag_10
            - tag_1005
            - tag_1006
            - tag_1007
            - tag_1008
            - tag_1009
            - tag_1010
            - tag_1011
            - tag_1012
            - tag_1013
            - tag_1014
            - tag_1015
            - tag_1016
            - tag_1017
            - tag_1018
            - tag_1019
            - tag_1020
            - tag_1021
            - tag_1025
            - tag_1027
            - tag_1036
            - tag_1039
            - tag_1043
            - tag_1044
            - tag_1049
            - tag_1050
            - tag_1051
            - tag_1052
            - tag_1053
            - tag_1054
            - tag_1055
            - tag_1056
            - tag_1058
            - tag_1059
            - tag_1060
            - tag_1061
            - tag_1062
            - tag_1064
            - tag_1065
            - tag_1066
            - tag_1067
            - tag_1068
            - tag_1070
            - tag_1072
            - tag_1166
            - tag_1171
            - tag_1172
            - tag_1173
            - tag_1178
            - tag_1181
            - tag_1212
            - tag_1213
            - tag_135
            - tag_1573
            - tag_1635
            - tag_178
            - tag_1837
            - tag_1838
            - tag_1839
            - tag_184
            - tag_20
            - tag_2096
            - tag_217
            - tag_226
            - tag_228
            - tag_239
            - tag_247
            - tag_255
            - tag_32
            - tag_35
            - tag_36
            - tag_37
            - tag_390
            - tag_494
            - tag_497
            - tag_499
            - tag_5
            - tag_50
            - tag_504
            - tag_51
            - tag_625
            - tag_65
            - tag_74
            - tag_76
            - tag_922
            - tag_927
            - tag_928
            - tag_93
            - tag_952
            - tag_953
            - tag_966
            - tag_967
            - tag_968
            - tag_969
            - tag_970
            - tag_971
            - tag_976
            - tag_977
            - tag_978
            - tag_979
            - tag_985
            - tag_986
            - tag_987
            - tag_988
            - tag_989
            - tag_990
            - tag_991
            - tag_995
            - tag_999
            - portions_1
            - portions_2
            - portions_4
            - portions_6
            - recipe_main_ingredient_name_fisk
            - recipe_main_ingredient_name_fugl
            - recipe_main_ingredient_name_fågel
            - recipe_main_ingredient_name_kjøtt
            - recipe_main_ingredient_name_lam
            - recipe_main_ingredient_name_pølse
            - recipe_main_ingredient_name_skalldyr
            - recipe_main_ingredient_name_storfe
            - recipe_main_ingredient_name_svin
            - recipe_main_ingredient_name_vegan
            - recipe_main_ingredient_name_vegetar
            - recipe_main_ingredient_name_vilt
  model_config:
    num_holdout_weeks: 5
    target: dish_ratio
    fold_strategy: timeseries
    data_split_shuffle: False
    transform_target: True
    transform_target_method: yeo-johnson
    verbose: False
    html: False
    ignore_features:
      - company_id
      - recipe_portion_id
      - variation_id
    n_select: 3
    model_list:
      - et
      - lightgbm
      - rf
      # - dt
      # - gbr
      # - en
  mlflow_config:
    experiment_tracking_dir: /Shared/ml_experiments/dishes/
    experiment_name: dishes_pycaret
    artifact_path: dishes_forecasting_model
    model_container_name: mlfeaturetesting
    registered_model_name: dishes_pycaret

AMK: *default
LMK: *default
