version: '3'
services:
  my-awesome-project:
    build:
      context: ../../
      dockerfile: projects/my-awesome-project/Dockerfile
    volumes:
      - ./my_awesome_project:/opt/projects/my-awesome-project/my_awesome_project

  my-awesome-project-app:
    build:
      context: ../../
      dockerfile: projects/my-awesome-project/Dockerfile
    volumes:
      - ./my_awesome_project:/opt/projects/my-awesome-project/my_awesome_project
      - ./app:/opt/projects/my-awesome-project/app
    command: ["python", "-m", "streamlit", "run", "app/main.py"]
    ports:
      - 8501:8501
