services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    command: "mlflow server --backend-store-uri file:///app/mlflow-server/experiments --artifacts-destination file:///app/mlflow-server/artifacts --host 0.0.0.0 --port 8000"

  test:
    image: model-registry-model-registry-test
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: packages/model-registry/Dockerfile
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/packages/model-registry
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8000
      - MLFLOW_REGISTRY_URI=http://mlflow:8000
