[tool.poetry]
name = "model_registry"
version = "0.1.0"
description = "A package to make it easier to integrate and test model registries"
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [{include = "model_registry"}]

[tool.poetry.dependencies]
python = "^3.10"
mlflow = "^2.19.0"
aligned = { version="^0.0.125", optional=true }
catalog-connector = { path = "../../packages/catalog-connector", develop = true }
polars = "^1.28.0"
polars-lts-cpu = "^1.28.0"

[tool.poetry.extras]
aligned = ["aligned"]

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}
pyright = "^1.1.376"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
