resources:
  jobs:
    reci-pick-train:
      name: reci-pick-train-${bundle.target}
      permissions:
        - group_name: data-scientists
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: reci-pick-train
          new_cluster:
            num_workers: 1
            spark_version: 15.4.x-scala2.12
            node_type_id: Standard_DS4_v2
            custom_tags:
              user: "Data scientists"
              tool: "Reci-pick Recommendation Engine"
              env: ${bundle.target}
              managed_by: "manually"
            docker_image:
              url: "${var.docker_image_url}"
              basic_auth:
                username: "{{secrets/auth_common/docker-registry-username}}"
                password: "{{secrets/auth_common/docker-registry-password}}"

      email_notifications:
        on_failure:
          - sylvia.liu@cheffelo.com

      tasks:
        - task_key: reci-pick-train-one-brand
          job_cluster_key: reci-pick-train
          notebook_task:
            notebook_path: ./train.py
            base_parameters:
              env: "${var.environment}"
              company: GL
              is_run_on_databricks: true
              is_register_model: false
              is_from_workflow: true
        - task_key: slack-notification-success
          depends_on:
            - task_key: reci-pick-train-one-brand
          run_if: ALL_SUCCESS
          run_job_task:
            job_id: ${var.slack_notification_job_id} #Reads from the variable defined in the databricks.yml file
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              header_message: ""
              body_message: ✅ Reci-pick Recommendation Algorithm train step finished!
              is_error: false
        - task_key: slack-notification-failied
          depends_on:
            - task_key: reci-pick-train-one-brand
          run_if: AT_LEAST_ONE_FAILED
          run_job_task:
            job_id: ${var.slack_notification_job_id} #Reads from the variable defined in the databricks.yml file
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              header_message: ❌ Reci-pick Recommendation Algorithm train step failed!
              body_message: Check databricks for details...
              is_error: true
              relevant_people: sylvia
