version: 2

models:
  - name: dim_brand
    description: Cleansed table which contains information about each brand.
    columns:

      - name: pk_dim_brand
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null

      - name: company_name
        description: Name of the company/brand
        data_tests:
          - not_null

      - name: country_name
        description: Name of the country that the company belongs to
        data_tests:
          - not_null