[tool.poetry]
name = "streamlit_pages"
version = "0.1.0"
description = "A package to manage streamlit pages state"
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [{include = "streamlit_pages"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.31.1"
pydantic = "^2.6.3"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
