table 'Agreement Measures'
	isHidden
	lineageTag: a8ab3df4-a35a-45a5-af58-17df4ee11ae8

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 6
		incrementalGranularity: month
		incrementalPeriods: 1
		sourceExpression =
			let
				Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				dim_preferences_Table = gold_Schema{[Name="fact_billing_agreements_daily",Kind="Table"]}[Data],
			    #"Filtered Rows" = Table.SelectRows(dim_preferences_Table, each [date] >= RangeStart and [date] < RangeEnd)
			in
			    #"Filtered Rows"

	measure 'Number of Customers' = DISTINCTCOUNT('Agreement Measures'[billing_agreement_id])
		formatString: #,0
		lineageTag: 3c376a1c-10ec-4f27-a197-d2bdd9455984

	measure 'Retention Number of Customers' = DISTINCTCOUNT('Agreements Weekly'[billing_agreement_id])
		formatString: #,0
		isHidden
		lineageTag: f6e71f0d-cf84-4777-af33-311720db8290

	measure 'Retention Number of Customers with Orders' = ```
			
			    CALCULATE(
			        [Retention Number of Customers],
			        'Agreements Weekly'[has_order] = 1
			    )
			```
		formatString: #,0
		isHidden
		lineageTag: 6675856e-88d1-49eb-80f7-d57ee90af51f

	measure '% Retention' =
			DIVIDE(
				[Retention Number of Customers with orders],
				[Retention Number of Customers],
				BLANK()
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 4962e557-7100-40b8-b7f6-73da7b8a7e65

	column pk_fact_billing_agreements_daily
		dataType: string
		isHidden
		lineageTag: d1c5e836-f16c-434a-8b81-66233110c718
		summarizeBy: none
		sourceColumn: pk_fact_billing_agreements_daily

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_date
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bc7bb454-df29-4293-84f1-7f9de47e00a1
		summarizeBy: none
		sourceColumn: fk_dim_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_billing_agreements
		dataType: string
		isHidden
		lineageTag: 0275368e-695f-406b-9c0a-3b08d6adf743
		summarizeBy: none
		sourceColumn: fk_dim_billing_agreements

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_companies
		dataType: string
		isHidden
		lineageTag: 5025dca3-7dde-4444-a689-63c0ef2b8b54
		summarizeBy: none
		sourceColumn: fk_dim_companies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 90f81dbc-5de9-4f97-ab3d-86e7d3e7eb1a
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d0bba6a5-600c-4016-b055-522dd30c08e2
		summarizeBy: sum
		sourceColumn: week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6e537bf2-359e-40cc-8a18-163f139f1d44
		summarizeBy: sum
		sourceColumn: year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column billing_agreement_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2957df7f-2f56-45ef-82a5-29c777cbcc3a
		summarizeBy: sum
		sourceColumn: billing_agreement_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column valid_from_billing_agreements
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 38b8b235-6385-461d-b01e-b8cfb9c178b4
		summarizeBy: none
		sourceColumn: valid_from_billing_agreements

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: string
		isHidden
		lineageTag: 93325f28-7c36-4761-8c59-6f8f58433395
		summarizeBy: none
		sourceColumn: company_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column days_since_first_order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 95ef0b54-e4c6-42fa-a9a8-1d9602917305
		summarizeBy: none
		sourceColumn: days_since_first_order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column has_order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ffbf4ee5-a333-470b-b791-62eae828241b
		summarizeBy: sum
		sourceColumn: has_order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_paused
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d4ec3744-c5a0-44ab-85df-e40cdf2f02ec
		summarizeBy: none
		sourceColumn: is_paused

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_freezed
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 70eaa1e1-db5a-40fc-8226-c9a82e6a014b
		summarizeBy: none
		sourceColumn: is_freezed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Agreement Measures' = m
		mode: import
		source =
				let
					Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
					catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
					gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
					dim_preferences_Table = gold_Schema{[Name="fact_billing_agreements_daily",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dim_preferences_Table, each [date] >= RangeStart and [date] < RangeEnd)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

