table 'Billing Agreements'
	lineageTag: e9e23909-ea1a-4aa8-9c71-604cd8245dce

	column pk_dim_billing_agreements
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: d1a47928-7371-42df-a8fb-338e902f82e0
		summarizeBy: none
		sourceColumn: pk_dim_billing_agreements

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Agreement Id'
		dataType: int64
		formatString: 0
		lineageTag: 49bc4193-4ea4-49b5-a837-df27efae7aa9
		summarizeBy: sum
		sourceColumn: Agreement Id

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5534c038-a78e-4770-a8ca-873f265eb447
		summarizeBy: none
		sourceColumn: company_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Point Id'
		dataType: int64
		formatString: 0
		lineageTag: 7f1fa672-5f50-4026-8bb4-c237d13ff6be
		summarizeBy: sum
		sourceColumn: Sales Point Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column valid_from
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		lineageTag: 50191510-b20d-491d-abae-85833eb89991
		summarizeBy: none
		sourceColumn: valid_from

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column valid_to
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		lineageTag: 1f60e753-69d6-422c-8d2d-c53b4a3a522e
		summarizeBy: none
		sourceColumn: valid_to

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: a5eaf2ae-1125-44bc-99d3-59ab436653c3
		summarizeBy: none
		sourceColumn: Payment Method

		annotation SummarizationSetBy = Automatic

	/// How the customer signed up:
	/// * `Sales`: Joined through a sales channel.
	/// * `Web`: Customer signed up through the website.
	/// * `Flex`: Legacy. Belongs to Godtlevert Flex which existed in 2019 and 2020.
	column 'Signup Source'
		dataType: string
		lineageTag: 1a914ada-c927-4a2b-9253-db4eec9a059b
		summarizeBy: none
		sourceColumn: Signup Source

		annotation SummarizationSetBy = Automatic

	column 'Signup Sales Person'
		dataType: string
		lineageTag: c8eb41e1-bf6e-4b16-8b7c-3314401ce778
		summarizeBy: none
		sourceColumn: Signup Sales Person

		annotation SummarizationSetBy = Automatic

	column 'Billing Agreement Status'
		dataType: string
		lineageTag: c8033f23-a99a-4496-9988-f77fa8cbf142
		summarizeBy: none
		sourceColumn: Billing Agreement Status

		annotation SummarizationSetBy = Automatic

	column 'Signup Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		isAvailableInMdx: false
		lineageTag: ce6f42f3-ecda-4f0c-8eb8-39efffc10c03
		summarizeBy: none
		sourceColumn: Signup Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column signup_year_day
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: bcb15a6c-02f7-4707-a4e0-593046fd2ba3
		summarizeBy: sum
		sourceColumn: signup_year_day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column signup_month_day
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: cd9770bc-a618-4bdf-a1a5-19e36e960b89
		summarizeBy: sum
		sourceColumn: signup_month_day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column signup_week_day
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 1e190920-69de-45c4-9bb9-a7832fc222f8
		summarizeBy: sum
		sourceColumn: signup_week_day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Signup Week'
		dataType: int64
		formatString: 0
		lineageTag: 28c5e978-6167-43f6-b71d-8c6bed7a56c0
		summarizeBy: sum
		sourceColumn: Signup Week

		annotation SummarizationSetBy = Automatic

	column 'Signup Month'
		dataType: int64
		formatString: 0
		lineageTag: 370a5d43-c083-4583-a04f-36f335bf432f
		summarizeBy: sum
		sourceColumn: Signup Month

		annotation SummarizationSetBy = Automatic

	column 'Signup Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 798e3d8b-39a3-4b3d-96ab-ed5b5be61fe7
		summarizeBy: sum
		sourceColumn: Signup Quarter

		annotation SummarizationSetBy = Automatic

	column 'Signup Year'
		dataType: int64
		formatString: 0
		lineageTag: 6e6c84c5-1173-4d3a-a0ef-6770e432318f
		summarizeBy: sum
		sourceColumn: Signup Year

		annotation SummarizationSetBy = Automatic

	column 'First Menu Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: d67151df-ae12-48b5-beb5-cf563a456e54
		summarizeBy: none
		sourceColumn: First Menu Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Menu Week'
		dataType: int64
		formatString: 0
		lineageTag: bbce92b8-d9b0-4148-afb6-e430f1b8fcad
		summarizeBy: sum
		sourceColumn: First Menu Week

		annotation SummarizationSetBy = Automatic

	column 'First Menu Month'
		dataType: int64
		formatString: 0
		lineageTag: a4b5b32d-c78f-45da-9e80-5e97f3bf0d87
		summarizeBy: sum
		sourceColumn: First Menu Month

		annotation SummarizationSetBy = Automatic

	column 'First Menu Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 8f0a19c5-6c68-40f7-bbdb-87ba3e6377fe
		summarizeBy: sum
		sourceColumn: First Menu Quarter

		annotation SummarizationSetBy = Automatic

	column 'First Menu Year'
		dataType: int64
		formatString: 0
		lineageTag: b33e20b9-81e5-406e-abee-b76e87cc1c89
		summarizeBy: sum
		sourceColumn: First Menu Year

		annotation SummarizationSetBy = Automatic

	column is_current
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: 373b4a87-26fd-4e55-9118-c6d440aee6d4
		summarizeBy: none
		sourceColumn: is_current

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column billing_agreement_preferences_updated_id
		dataType: string
		isHidden
		lineageTag: fadb0409-da35-4138-b87c-dabf327fa364
		summarizeBy: none
		sourceColumn: billing_agreement_preferences_updated_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Meals
		dataType: int64
		formatString: 0
		lineageTag: 685f85f5-23c7-40e5-8cf6-0bf4fcf9123a
		summarizeBy: sum
		sourceColumn: Meals

		annotation SummarizationSetBy = Automatic

	column Portions
		dataType: int64
		formatString: 0
		lineageTag: 0f02ea42-f7e3-4561-863f-4d22fcfa953d
		summarizeBy: sum
		sourceColumn: Portions

		annotation SummarizationSetBy = Automatic

	column 'Subscribed Mealbox'
		dataType: string
		lineageTag: 34b510ce-1fc6-4269-9da1-78f3691b222c
		summarizeBy: none
		sourceColumn: Subscribed Mealbox

		annotation SummarizationSetBy = Automatic

	column 'Is OneSub'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 125174ea-629c-433d-9226-9b9c2d128b84
		summarizeBy: none
		sourceColumn: Is OneSub

		annotation SummarizationSetBy = Automatic

	partition 'Billing Agreements' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    dim_calendar_Table = gold_Schema{[Name="dim_billing_agreements",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dim_calendar_Table,{
						{"billing_agreement_id", "Agreement Id"}, 
						{"payment_method", "Payment Method"}, 
						{"signup_source", "Signup Source"}, 
						{"signup_salesperson", "Signup Sales Person"}, 
						{"billing_agreement_status_name", "Billing Agreement Status"}, 
						{"signup_date", "Signup Date"}, 
						{"signup_week", "Signup Week"}, 
						{"signup_month", "Signup Month"}, 
						{"signup_quarter", "Signup Quarter"}, 
						{"signup_year", "Signup Year"}, 
						{"first_menu_week_monday_date", "First Menu Date"}, 
						{"first_menu_week_week", "First Menu Week"}, 
						{"first_menu_week_month", "First Menu Month"}, 
						{"first_menu_week_quarter", "First Menu Quarter"}, 
						{"first_menu_week_year", "First Menu Year"}, 
						{"sales_point_id", "Sales Point Id"}, 
						{"is_onesub", "Is OneSub"}, 
						{"meals", "Meals"}, 
						{"portions", "Portions"}, 
						{"product_name", "Subscribed Mealbox"}
					})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

