table 'Budget Measures'
	lineageTag: Budget-Measures-Table

	/// Budgeted Average Transaction Value for Orders Ex Vat.
	/// The number is gross, meaning that it only includes order lines of type
	/// debit and transportation and not order lines such as discount or credit.
	measure 'ATV Gross Ex Vat (Target)' = AVERAGE('Budget Measures'[Target ATV Gross Ex VAT])
		formatString: #,0
		lineageTag: 5d95c771-f00a-4315-9e5b-5d1b1b93ce9a

	/// The number of budgeted orders.
	measure 'Number of Orders (Target)' = SUM('Budget Measures'[Target Number Of Orders])
		formatString: #,0
		lineageTag: 80f5fa4e-3b75-499c-89e6-ebd0ce415a49

	/// Budgeted gross revenue from orders ex vat.
	/// Is calculated by multiplying Number of Orders with ATV.
	/// The number is gross, meaning that it only includes order lines of type
	/// debit and transportation and not order lines such as discount or credit.
	measure 'Order Value Gross Ex Vat (Target)' = SUM('Budget Measures'[Target Order Value Gross Ex Vat])
		formatString: #,0
		lineageTag: 9d9f5379-7bf6-4875-976a-a8ee35413e53

	/// Increase/decrease in sales compared to budgeted sales
	measure 'Number of Orders (Diff Target)' = [Number of Orders] - [Number of Orders (Target)]
		formatString: #,0
		lineageTag: 1a1cb7c8-c237-498e-8813-41698ec8fb36

	/// Increase/decrease in sales compared to budgeted sales (Actual over Budget%)
	measure 'Number of Orders (AoB%)' = DIVIDE([Number of Orders (Diff Target)],[Number of Orders (Target)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5f4dd8ba-14ea-45ce-81e0-11c1a0f690f7

	/// Increase/decrease in sales revenue compared to budgeted sales revenue
	measure 'Order Value Gross Ex Vat (Diff Target)' = [Order Value Gross Ex Vat] - [Order Value Gross Ex Vat (Target)]
		formatString: #,0
		lineageTag: 107c94d0-7512-4623-9c3f-1abcfbdc4804

	/// Increase/decrease in sales revenue compared to budgeted sales revenue (Actual over Budget%)
	measure 'Order Value Gross Ex Vat (AoB%)' = DIVIDE([Order Value Gross Ex Vat],[Order Value Gross Ex Vat (Target)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f6e96297-0348-4c8e-b56d-eb9ec130f3d7

	/// Increase/decrease in ATV compared to budgeted ATV
	measure 'ATV Gross Ex Vat (Diff Target)' = [ATV Gross Ex Vat] - [ATV Gross Ex Vat (Target)]
		formatString: #,0
		lineageTag: cfec4b82-0efc-4c0e-a713-72a9e2257465

	/// Increase/decrease in ATV compared to budgeted ATV (Actual over Budget%)
	measure 'ATV Gross Ex Vat (AoB%)' = DIVIDE([ATV Gross Ex Vat (Diff Target)],[ATV Gross Ex Vat (Target)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3818d45c-f8bb-4c79-a3ef-2446c5471a7c

	/// The primary key of the fact_budget table
	column pk_fact_budget
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 62644411-c04e-4180-a1a3-dd64e4d61411
		summarizeBy: none
		sourceColumn: pk_fact_budget

	/// Unique id for each entry in the budget.
	/// Granularity is company, financial week and customer segment
	column budget_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5d3d4f4a-e7dc-49e9-af24-0c3416274358
		summarizeBy: none
		sourceColumn: budget_id

	/// The corresponding id to which type of budget process the data belongs to (F1, F2, F3, Budget)
	column budget_type_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: e2240562-3a76-4c1b-bb31-aae1b351845e
		summarizeBy: none
		sourceColumn: budget_type_id

	/// The corresponding id to which segment the data belongs to
	column budget_segment_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5571dee3-782b-4bb6-af77-f3fe746cb455
		summarizeBy: none
		sourceColumn: budget_segment_id

	/// The corresponding id to which company the data belongs to
	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 98bf45cf-ca2e-4bb1-a3ad-2d3c3220e4f2
		summarizeBy: none
		sourceColumn: company_id

	/// The year corresponding to the Monday of the same week.
	/// For example, January 1st, 2025, falls on a Wednesday,
	/// and the Monday of that week is December 30th, 2024.
	/// Therefore, the financial quarter for January 1st, 2025, is 4,
	/// as it follows the quarter of the corresponding Monday.
	column 'Financial Year'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3ea65108-9538-4961-9d41-f69566a39a01
		summarizeBy: none
		sourceColumn: financial_year

	/// The week number of the date, adjusted to align with the Monday of the corresponding week.
	/// A financial week 53 is introduced when necessary to replace ISO week 1 of the following year.
	column 'Financial Week'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 5ce5fe10-9a3e-4424-b44c-432962d1d10d
		summarizeBy: none
		sourceColumn: financial_week

	/// The gross atv per week and customer segment
	column 'Target ATV Gross Ex VAT'
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: dc3a98f8-4c48-4381-8960-e4b7457105c3
		summarizeBy: none
		sourceColumn: budget_atv_gross_ex_vat

	/// The number of orders per week per customer segment
	column 'Target Number Of Orders'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 9db3cbf7-e168-45b0-b033-33b8f52b70f0
		summarizeBy: none
		sourceColumn: budget_number_of_orders

	/// The gross order value ex VAT per week per customer segment
	column 'Target Order Value Gross Ex VAT'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: budget_order_value_gross_ex_vat

	/// Foreign key connecting the budget dates to dim_dates
	column fk_dim_dates
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 5ead1f23-cfa8-4b46-8f83-6f9f008c6114
		summarizeBy: none
		sourceColumn: fk_dim_dates

	/// Foreign key connecting the companies table to the budget table
	column fk_dim_companies
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: d481adee-fe49-4c20-9ce8-16c20625ba92
		summarizeBy: none
		sourceColumn: fk_dim_companies

	/// Foreign key connecting the budget table to the budget_type table
	column fk_dim_budget_types
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: c93f2181-7a4c-4c5c-b4a1-09e053a31d86
		summarizeBy: none
		sourceColumn: fk_dim_budget_types

	partition 'Budget Measures' = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    fact_budget_Table = gold_Schema{[Name="fact_budget",Kind="Table"]}[Data]
				in
				    fact_budget_Table

