/// Cases and case lines reltated to deliveries reported by the customer, customer service or partners.
/// A case line includes communication records (SMS and notes), redelivery events, and complaints with reimbursement options.
/// A delivery can only have one related case, but a case can have several case lines.
table 'Case Measures'
    lineageTag: Case-Measures-Table

    /// The number of cases lines. One order can have several case lines, but only one case.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Case Lines' = DISTINCTCOUNTNOBLANK('Case Measures'[case_line_id])
		isHidden
        formatString: #,0    
        displayFolder: Cases

    /// The number of orders which had at least one case related to it.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Orders With Cases' = DISTINCTCOUNTNOBLANK('Case Measures'[ops_order_id])
		formatString: #,0    
        displayFolder: Cases\Orders with Cases

    /// The number of of orders which had a case related to it in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Orders With Cases (Current Month)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The number of of orders which had a case related to it last year.
    measure 'Number of Orders With Cases (PY)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The difference in number of orders with cases in the selected year and the year before.
    measure 'Number of Orders With Cases (Diff PY)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The percentage change in number of orders with cases in the selected year and the year before.
    measure 'Number of Orders With Cases (YOY%)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The cummulative number of orders with cases from the beginning of the year up to the current period.
    measure 'Number of Orders With Cases (YTD)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The cummulative number of orders with cases from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Orders With Cases (PYTD)' = CALCULATE([Number of Orders With Cases], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    ///The share of deliveries that have a case.
    measure 'Share of Orders With Cases' = DIVIDE([Number of Orders With Cases], [Number of Orders])
        formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Orders with Cases
    
    /// The share of orders with cases last year.
    measure 'Share of Orders With Cases (PY)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Orders with Cases

    /// The share of orders with cases in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Share of Orders With Cases (Current Month)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Orders with Cases

    /// The difference in share of orders with cases in the selected year and the year before.
    measure 'Share of Orders With Cases (Diff PY)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The percentage change in share of orders with cases in the selected year and the year before.
    measure 'Share of Orders With Cases (YOY%)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Cases\Orders with Cases

    /// The share of orders with cases from the beginning of the year up to the current period.
    measure 'Share of Orders With Cases (YTD)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Orders with Cases

    /// The share of orders with cases from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Share of Orders With Cases (PYTD)' = CALCULATE([Share of Orders With Cases], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Orders with Cases

    /// The number of cases per 1000 orders.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Cases per 1000 Orders' = DIVIDE([Number of Orders With Cases], [Number of Orders])*1000
        formatString: #,0
        displayFolder: Cases\Per 1000 Orders

    /// The number of cases per 1000 orders last year.
    measure 'Number of Cases per 1000 Orders (PY)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Per 1000 Orders

    /// The number of cases per 1000 orders in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Cases per 1000 Orders (Current Month)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Per 1000 Orders

    /// The difference in number of cases per 1000 orders in the selected year and the year before.
    measure 'Number of Cases per 1000 Orders (Diff PY)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Cases\Per 1000 Orders

    /// The percentage change in number of cases per 1000 orders in the selected year and the year before.
    measure 'Number of Cases per 1000 Orders (YOY%)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Cases\Per 1000 Orders

    /// The number of cases per 1000 orders from the beginning of the year up to the current period.
    measure 'Number of Cases per 1000 Orders (YTD)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Per 1000 Orders

    /// The number of cases per 1000 orders from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Cases per 1000 Orders (PYTD)' = CALCULATE([Number of Cases per 1000 Orders], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Cases\Per 1000 Orders

    /// The number of orders which had at least one redelivery related to it.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Orders With Redelivery' = 
            CALCULATE(
                DISTINCTCOUNTNOBLANK('Case Measures'[ops_order_id]),
                'Case Measures'[is_accepted_redelivery] = TRUE()
            )
		formatString: #,0    
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The number of of orders which had a redelivery related to it last year.
    measure 'Number of Orders With Redelivery (PY)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The number of of orders which had a redelivery related to it in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Orders With Redelivery (Current Month)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The difference in number of orders with redeliveries in the selected year and the year before.
    measure 'Number of Orders With Redelivery (Diff PY)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The percentage change in number of orders with redeliveries in the selected year and the year before.
    measure 'Number of Orders With Redelivery (YOY%)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The cummulative number of orders with redeliveries from the beginning of the year up to the current period.
    measure 'Number of Orders With Redelivery (YTD)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The cummulative number of orders with redeliveries from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Orders With Redelivery (PYTD)' = CALCULATE([Number of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    ///The share of deliveries that have a redelivery.
    measure 'Share of Orders With Redelivery' = DIVIDE([Number of Orders With Redelivery], [Number of Orders])
        formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Orders with Redeliveries
    
    /// The share of orders with redeliveries last year.
    measure 'Share of Orders With Redelivery (PY)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The share of orders with redeliveries in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Share of Orders With Redelivery (Current Month)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Orders with Redeliveries
      
    /// The difference in share of orders with redeliveries in the selected year and the year before.
    measure 'Share of Orders With Redelivery (Diff PY)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The percentage change in share of orders with redeliveries in the selected year and the year before.
    measure 'Share of Orders With Redelivery (YOY%)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The share of orders with redeliveries from the beginning of the year up to the current period.
    measure 'Share of Orders With Redelivery (YTD)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The share of orders with redeliveries from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Share of Orders With Redelivery (PYTD)' = CALCULATE([Share of Orders With Redelivery], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Orders with Redeliveries

    /// The number of redeliveries per 1000 orders.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Redelivery per 1000 Orders' = DIVIDE([Number of Orders With Redelivery], [Number of Orders])*1000
        formatString: #,0
        displayFolder: Redeliveries\Per 1000 Orders

    /// The number of redeliveries per 1000 orders last year.
    measure 'Number of Redelivery per 1000 Orders (PY)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Per 1000 Orders

    /// The number of redeliveries per 1000 orders in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Redelivery per 1000 Orders (Current Month)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Per 1000 Orders

    /// The difference in number of redeliveries per 1000 orders in the selected year and the year before.
    measure 'Number of Redelivery per 1000 Orders (Diff PY)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Redeliveries\Per 1000 Orders

    /// The percentage change in number of redeliveries per 1000 orders in the selected year and the year before.
    measure 'Number of Redelivery per 1000 Orders (YOY%)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Redeliveries\Per 1000 Orders

    /// The number of redeliveries per 1000 orders from the beginning of the year up to the current period.
    measure 'Number of Redelivery per 1000 Orders (YTD)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Per 1000 Orders

    /// The number of redeliveries per 1000 orders from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Redelivery per 1000 Orders (PYTD)' = CALCULATE([Number of Redelivery per 1000 Orders], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Redeliveries\Per 1000 Orders
    
    /// The number of case lines which is related to a complaint. One order can have several case line, but only one case.
    measure 'Number of Complaints' = 
            CALCULATE(
                DISTINCTCOUNTNOBLANK('Case Measures'[case_line_id]),
                'Case Measures'[is_complaint] = TRUE()
            )
        formatString: #,0    
        displayFolder: Complaints\Number of Complaints

    /// The number of complaints last year.
    measure 'Number of Complaints (PY)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The number of complaints in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Complaints (Current Month)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The difference in number of complaints in the selected year and the year before.
    measure 'Number of Complaints (Diff PY)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The percentage change in number of complaints in the selected year and the year before.
    measure 'Number of Complaints (YOY%)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The cummulative number of complaints from the beginning of the year up to the current period.
    measure 'Number of Complaints (YTD)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The cummulative number of complaints from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Complaints (PYTD)' = CALCULATE([Number of Complaints], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Complaints\Number of Complaints

    /// The number of orders which had at least one complaint related to it.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Orders With Complaints' = 
            CALCULATE(
                DISTINCTCOUNTNOBLANK('Case Measures'[ops_order_id]),
                'Case Measures'[is_complaint] = TRUE()

            )
		formatString: #,0    
        displayFolder: Complaints\Orders with Complaints

    /// The number of of orders which had a complaint related to it last year.
    measure 'Number of Orders With Complaints (PY)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    /// The number of of orders which had a complaint related to it in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Orders With Complaints (Current Month)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    /// The difference in number of orders with complaints in the selected year and the year before.
    measure 'Number of Orders With Complaints (Diff PY)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    /// The percentage change in number of orders with complaints in the selected year and the year before.
    measure 'Number of Orders With Complaints (YOY%)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    /// The cummulative number of orders with complaints from the beginning of the year up to the current period.
    measure 'Number of Orders With Complaints (YTD)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    /// The cummulative number of orders with complaints from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Orders With Complaints (PYTD)' = CALCULATE([Number of Orders With Complaints], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Complaints\Orders with Complaints

    ///The share of deliveries that have a complaint.
    measure 'Share of Orders With Complaints' = DIVIDE([Number of Orders With Complaints], [Number of Orders])
        formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints
    
    /// The share of orders with complaints last year.
    measure 'Share of Orders With Complaints (PY)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints

    /// The share of orders with complaints in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Share of Orders With Complaints (Current Month)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints
        
    /// The difference in share of orders with complaints in the selected year and the year before.
    measure 'Share of Orders With Complaints (Diff PY)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints

    /// The percentage change in share of orders with complaints in the selected year and the year before.
    measure 'Share of Orders With Complaints (YOY%)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints

    /// The share of orders with complaints from the beginning of the year up to the current period.
    measure 'Share of Orders With Complaints (YTD)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints

    /// The share of orders with complaints from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Share of Orders With Complaints (PYTD)' = CALCULATE([Share of Orders With Complaints], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Orders with Complaints

    /// The number of complaints per 1000 orders.
    /// It can be a complaint, redelivery or an sms or note.
    measure 'Number of Complaints per 1000 Orders' = DIVIDE([Number of Orders With Complaints], [Number of Orders])*1000
        formatString: #,0
        displayFolder: Complaints\Per 1000 Orders
    /// The number of complaints per 1000 orders last year.
    measure 'Number of Complaints per 1000 Orders (PY)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Per 1000 Orders

    /// The number of complaints per 1000 orders in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Number of Complaints per 1000 Orders (Current Month)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Per 1000 Orders

    /// The difference in number of complaints per 1000 orders in the selected year and the year before.
    measure 'Number of Complaints per 1000 Orders (Diff PY)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Per 1000 Orders

    /// The percentage change in number of complaints per 1000 orders in the selected year and the year before.
    measure 'Number of Complaints per 1000 Orders (YOY%)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Per 1000 Orders

    /// The number of complaints per 1000 orders from the beginning of the year up to the current period.
    measure 'Number of Complaints per 1000 Orders (YTD)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Per 1000 Orders

    /// The number of complaints per 1000 orders from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Number of Complaints per 1000 Orders (PYTD)' = CALCULATE([Number of Complaints per 1000 Orders], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Per 1000 Orders

    /// The total amount credited, including VAT.
    measure 'Complaint Cost Inc Vat' = SUM('Case Measures'[Credit Amount Inc Vat])
        formatString: #,0
        displayFolder: Complaints\Cost Inc Vat
    
    /// The total amount credited last year.
    measure 'Complaint Cost Inc Vat (PY)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The total amount credited in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Complaint Cost Inc Vat (Current Month)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The difference in amount credited in the selected year and the year before.
    measure 'Complaint Cost Inc Vat (Diff PY)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The percentage change in amount credited in the selected year and the year before.
    measure 'Complaint Cost Inc Vat (YOY%)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The total amount credited from the beginning of the year up to the current period.
    measure 'Complaint Cost Inc Vat (YTD)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The total amount credited from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Complaint Cost Inc Vat (PYTD)' = CALCULATE([Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per order, including VAT. The cost of all complaints in a given period divided by the number of orders in that period.
    measure 'Average Complaint Cost Per Order Inc Vat' = DIVIDE([Complaint Cost Inc Vat], [Number of Orders])
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat
    
    /// The average amount credited per order, including VAT, last year.
    measure 'Average Complaint Cost Per Order Inc Vat (PY)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per order, including VAT, in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Average Complaint Cost Per Order Inc Vat (Current Month)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The difference in average amount credited per order in the selected year and the year before.
    measure 'Average Complaint Cost Per Order Inc Vat (Diff PY)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The percentage change in average amount credited per order in the selected year and the year before.
    measure 'Average Complaint Cost Per Order Inc Vat (YOY%)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per order, including VAT, from the beginning of the year up to the current period.
    measure 'Average Complaint Cost Per Order Inc Vat (YTD)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per order, including VAT, from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Average Complaint Cost Per Order Inc Vat (PYTD)' = CALCULATE([Average Complaint Cost Per Order Inc Vat], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per complaint, including VAT.
    measure 'Average Complaint Cost Inc Vat' = DIVIDE([Complaint Cost Inc Vat], [Number of Complaints])
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat
    
    /// The average amount credited per complaint last year.
    measure 'Average Complaint Cost Inc Vat (PY)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="PY")
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per complaint in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Average Complaint Cost Inc Vat (Current Month)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="Current Month")
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The difference in average amount credited per complaint in the selected year and the year before.
    measure 'Average Complaint Cost Inc Vat (Diff PY)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="Diff PY")
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The percentage change in average amount credited per complaint in the selected year and the year before.
    measure 'Average Complaint Cost Inc Vat (YOY%)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="YOY%")
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat
    
    /// The average amount credited per complaint from the beginning of the year up to the current period.
    measure 'Average Complaint Cost Inc Vat (YTD)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="YTD")
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The average amount credited per complaint from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Average Complaint Cost Inc Vat (PYTD)' = CALCULATE ('Case Measures'[Average Complaint Cost Inc Vat], 'Time Intelligence'[Time Calculation]="PYTD")
        formatString: #,0.00
        displayFolder: Complaints\Cost Inc Vat

    /// The total amount credited, excluding VAT.
    /// The VAT is deducted based on a fixed VAT rate per company which is 0.25 for Renemt, 0.12 for Linas Matkasse and 0.15 for Godtlevert and Adams Matkasse.
    measure 'Complaint Cost Ex Vat' = SUM('Case Measures'[Credit Amount Ex Vat])
        formatString: #,0
        displayFolder: Complaints\Cost Ex Vat
    
    /// The total amount credited last year.
    measure 'Complaint Cost Ex Vat (PY)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The total amount credited in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Complaint Cost Ex Vat (Current Month)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The difference in amount credited in the selected year and the year before.
    measure 'Complaint Cost Ex Vat (Diff PY)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The percentage change in amount credited in the selected year and the year before.
    measure 'Complaint Cost Ex Vat (YOY%)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The total amount credited from the beginning of the year up to the current period.
    measure 'Complaint Cost Ex Vat (YTD)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The total amount credited from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Complaint Cost Ex Vat (PYTD)' = CALCULATE([Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per order, including VAT. The cost of all complaints in a given period divided by the number of orders in that period.
    measure 'Average Complaint Cost Per Order Ex Vat' = DIVIDE([Complaint Cost Ex Vat], [Number of Orders])
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat
    
    /// The average amount credited per order, including VAT, last year.
    measure 'Average Complaint Cost Per Order Ex Vat (PY)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per order, including VAT, in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Average Complaint Cost Per Order Ex Vat (Current Month)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The difference in average amount credited per order in the selected year and the year before.
    measure 'Average Complaint Cost Per Order Ex Vat (Diff PY)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The percentage change in average amount credited per order in the selected year and the year before.
    measure 'Average Complaint Cost Per Order Ex Vat (YOY%)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per order, including VAT, from the beginning of the year up to the current period.
    measure 'Average Complaint Cost Per Order Ex Vat (YTD)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per order, including VAT, from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Average Complaint Cost Per Order Ex Vat (PYTD)' = CALCULATE([Average Complaint Cost Per Order Ex Vat], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per complaint, including VAT.
    measure 'Average Complaint Cost Ex Vat' = DIVIDE([Complaint Cost Ex Vat], [Number of Complaints])
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat
    
    /// The average amount credited per complaint last year.
    measure 'Average Complaint Cost Ex Vat (PY)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="PY")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per complaint in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Average Complaint Cost Ex Vat (Current Month)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="Current Month")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The difference in average amount credited per complaint in the selected year and the year before.
    measure 'Average Complaint Cost Ex Vat (Diff PY)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="Diff PY")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The percentage change in average amount credited per complaint in the selected year and the year before.
    measure 'Average Complaint Cost Ex Vat (YOY%)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="YOY%")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat
    
    /// The average amount credited per complaint from the beginning of the year up to the current period.
    measure 'Average Complaint Cost Ex Vat (YTD)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="YTD")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The average amount credited per complaint from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Average Complaint Cost Ex Vat (PYTD)' = CALCULATE ('Case Measures'[Average Complaint Cost Ex Vat], 'Time Intelligence'[Time Calculation]="PYTD")
        formatString: #,0.00
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue, excluding VAT.
    measure 'Complaint Cost Share of Order Value Ex Vat' = DIVIDE([Complaint Cost Ex Vat], [Order Value Gross Ex Vat])
        formatString: 0.00%;-0.00%;0.00%
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue last year.
    measure 'Complaint Cost Share of Order Value Ex Vat (PY)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue in the month of todays date.
    /// Need to be filtered on year if its wanted to see numbers for a specific year.
    measure 'Complaint Cost Share of Order Value Ex Vat (Current Month)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="Current Month") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The difference in share of complaint cost per revenue in the selected year and the year before.
    measure 'Complaint Cost Share of Order Value Ex Vat (Diff PY)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="Diff PY") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The percentage change in share of complaint cost per revenue in the selected year and the year before.
    measure 'Complaint Cost Share of Order Value Ex Vat (YOY%)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="YOY%") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue from the beginning of the year up to the current period.
    measure 'Complaint Cost Share of Order Value Ex Vat (YTD)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="YTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue from the beginning of the year up to the current period, for the same period in the previous year.
    measure 'Complaint Cost Share of Order Value Ex Vat (PYTD)' = CALCULATE([Complaint Cost Share of Order Value Ex Vat], 'Time Intelligence'[Time Calculation]="PYTD") 
		formatString: #,0
        displayFolder: Complaints\Cost Ex Vat

    /// The share of complaint cost per revenue, including VAT.
	measure 'Complaint Cost Share of Order Value Inc Vat' = DIVIDE([Complaint Cost Inc Vat], [Order Value Gross Ex Vat])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Complaints\Cost Inc Vat

	/// The share of complaint cost per revenue last year, including VAT.
	measure 'Complaint Cost Share of Order Value Inc Vat (PY)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="PY")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat

	/// The share of complaint cost per revenue (including VAT) in the month of todays date.
	/// Need to be filtered on year if its wanted to see numbers for a specific year.
	measure 'Complaint Cost Share of Order Value Inc Vat (Current Month)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="Current Month")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat

	/// The difference in share of complaint cost per revenue (including VAT) in the selected year and the year before.
	measure 'Complaint Cost Share of Order Value Inc Vat (Diff PY)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="Diff PY")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat

	/// The percentage change in share of complaint cost per revenue (including VAT) in the selected year and the year before.
	measure 'Complaint Cost Share of Order Value Inc Vat (YOY%)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="YOY%")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat

	/// The share of complaint cost per revenue (including VAT) from the beginning of the year up to the current period.
	measure 'Complaint Cost Share of Order Value Inc Vat (YTD)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="YTD")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat

	/// The share of complaint cost per revenue (including VAT) from the beginning of the year up to the current period, for the same period in the previous year.
	measure 'Complaint Cost Share of Order Value Inc Vat (PYTD)' = CALCULATE([Complaint Cost Share of Order Value Inc Vat], 'Time Intelligence'[Time Calculation]="PYTD")
		formatString: #,0
		displayFolder: Complaints\Cost Inc Vat
       
    /// The quantity of the ingredients reported in complaints. I.e., if a customer reported two bad carrots the number will be two.
    measure 'Complaint Ingredient Quantity' = SUM('Case Measures'[Ingredient Quantity])
		formatString: #,0
        displayFolder: Ingredients

    /// The share of ingredients in the customer orders with complaints
    /// Calculated as [Complaint Ingredient Quantity]/[Ingredient Quantity in Orders]
    measure 'Share of Ordered Ingredients with Complaints' = 
            DIVIDE(
                [Complaint Ingredient Quantity],
                [Ingredient Quantity in Orders Whole Units]
            )
        formatString: 0.00%;-0.00%;0.00%
        displayFolder: Ingredients

    /// Primary key of the fact_case table.
    column pk_fact_cases
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: pk_fact_cases
    
    /// The unique id of the case table. Contains a unique id for each case.
    column case_id
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: case_id

    /// The unique id of the case lines table.
    column case_line_id
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: case_line_id

    /// This is the primary key in the OPS database for each placed order.
    /// Is null if there was no order generated in OPS. 
    /// This could for instance be if a customer only buy a gift card or an order was cancelled.
    column ops_order_id
        dataType: int64
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: ops_order_id

    /// The amount the customer will get in reimbursement. I.e., the cost of the case.
    column 'Credit Amount Inc Vat'
        dataType: int64
        isHidden
        summarizeBy: none
        sourceColumn: credit_amount_inc_vat
    
    /// The amount the customer will get in reimbursement. I.e., the cost of the case. 
    /// The VAT is deducted based on a fixed VAT rate per company which is 0.25 for Renemt, 0.12 for Linas Matkasse and 0.15 for Godtlevert and Adams Matkasse.
    column 'Credit Amount Ex Vat'
        dataType: int64
        isHidden
        summarizeBy: none
        sourceColumn: credit_amount_ex_vat

    /// Comments regarding the case. 
    /// Can come from external partners or internally from logistics/customer service, 
    /// which is defined by source_updated_by.
    column 'Case Line Comment'
        dataType: string
        isHidden
        summarizeBy: none
        sourceColumn: case_line_comment

    /// True if the case line belongs to a complaint and false for other case lines such as sms, notes or redeliveries. 
    /// Complaints are delivery incidents reported by the customers, customer service or our external partners (i.e. transport company) 
    /// which can result in compensating the customer. The complaint can relate to the delivery itself or to the products being delivered.
    column is_complaint
        dataType: boolean
        isHidden
        formatString: """TRUE"";""TRUE"";""FALSE"""
        summarizeBy: none
        sourceColumn: is_complaint

    /// True if the case line belongs to a redelivery case that has been approved and rescheduled by the logistics team.
    column is_accepted_redelivery
        dataType: boolean
        isHidden
        formatString: """TRUE"";""TRUE"";""FALSE"""
        summarizeBy: none
        sourceColumn: is_accepted_redelivery

    /// Comment connected to redelivery. 
    /// Can come from external partners or internally from logistics/customer service,
    /// which is defined by source_updated_by.
    column 'Redelivery Comment'
        dataType: string
        isHidden
        summarizeBy: none
        sourceColumn: redelivery_comment

    /// The quantity of ingredients registered in the case.
    column 'Ingredient Quantity'
        dataType: int64
        isHidden
        summarizeBy: none
        sourceColumn: ingredient_quantity

    /// The unique id of each row in dim billing agreements.
    column fk_dim_billing_agreements
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_billing_agreements
    
    /// The unique id of each row in dim companies.
    column fk_dim_companies
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_companies
    
    /// Primary key of the dim case details table.
    column fk_dim_case_details
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_case_details
    
    /// Primary key of the dim dates table.This is an integer on the form YYYYMMDD (e.g. 20250117).
    column fk_dim_dates
        dataType: int64
        isHidden
        isAvailableInMdx: false
        formatString: 0
        summarizeBy: none
        sourceColumn: fk_dim_dates
    
    /// Primary key of the dim ingredients table.
    column fk_dim_ingredients
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_ingredients

    /// Primary key of the dim customer journey segments table.
    column fk_dim_customer_journey_segments
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_customer_journey_segments

    column fk_dim_transportation
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_transportation

    partition 'Case Measures' = m
        mode: directQuery
        source =
                let
                    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
                    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
                    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
                    fact_cases_Table = gold_Schema{[Name="fact_cases",Kind="Table"]}[Data]
                in
                    fact_cases_Table
