/// All forecasts per product variation and menu week produced by the analytics team and including overwrites made by external teams.
table 'Forecast Measures'
    lineageTag: Forecast-Measures-Table

    /// The forecasted number of orders for a given menu week.
    measure 'Number of Forecasted Orders' = SUM('Forecast Measures'[Order Quantity Forecast])
        formatString: #,0

    /// The forecasted quantity of a given product variation for a given menu week.
    measure 'Number of Forecasted Product Variations' = SUM('Forecast Measures'[Product Variation Quantity Forecast])
        formatString: #,0

    column 'Order Quantity Forecast'
        dataType: int64
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: order_quantity_forecast

    column 'Product Variation Quantity Forecast'
        dataType: int64
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: product_variation_quantity_forecast

    /// True if the forecast is the most recent for a given menu week.
    column 'Is Most Recent Forecast'
        dataType: boolean
        formatString: """TRUE"";""TRUE"";""FALSE"""
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: is_most_recent_menu_week_forecast

    /// Primary key of the dim_forecast_runs table
    column fk_dim_forecast_runs
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_forecast_runs

    /// Primary key of the dim_companies table
    column fk_dim_companies
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_companies

    /// Primary key of the dim_products table
    column fk_dim_products
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_products

    /// Primary key of the dim_dates table
    column fk_dim_dates_menu_week
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_dates_menu_week
    
    /// Primary key of the dim_dates_forecast_generated_at table
    column fk_dim_dates_forecast_generated_at
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_dates_forecast_generated_at

    /// Primary key of the dim_recipes table
    column fk_dim_recipes
        dataType: string
        isHidden
        isAvailableInMdx: false
        summarizeBy: none
        sourceColumn: fk_dim_recipes

    partition 'Forecast Variation Measures' = m
        mode: directQuery
        source =
                let
                    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
                    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
                    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
                    fact_forecast_variations_Table = gold_Schema{[Name="fact_forecast_variations",Kind="Table"]}[Data]
                in
                    fact_forecast_variations_Table
