/// Table of measures related to all loyalty points transactions.
/// Table is hidden. All measures are displayed in the 'Loyalty Measures' table 
table 'Loyalty Point Measures'
	isHidden
	lineageTag: Loyalty-Point-Measures-Table

	/// Number of points earned, spent, expired, etc. on all loyalty points transactions
	measure 'All Loyalty Points' =
			CALCULATE(
				SUM('Loyalty Point Measures'[Transaction Points])
			)
		formatString: #,0
		isHidden
		lineageTag: 8737f78b-8329-45ef-baf4-995778c67d08

	/// Number of spendable loyalty points earned on pointworthy transactions, such as ordering mealboxes or referring friends.
	/// Spendable points are points that can be spent in the Points Store.
	measure 'Loyalty Points Earned' =
			CALCULATE(
			    [All Loyalty Points],
			    ISBLANK('Loyalty Point Measures'[loyalty_points_parent_id])
			)
		formatString: #,0
		isHidden
		lineageTag: 5e8fa074-ac41-4516-acac-2508cfb505a9

	/// Number of loyalty points spent in the Points Store.
	measure 'Loyalty Points Spent' =
			CALCULATE(
			    [All Loyalty Points],
			    NOT ISBLANK('Loyalty Point Measures'[loyalty_order_id])
			)
		formatString: #,0
		isHidden
		lineageTag: d7cb57b0-5563-4441-bb3e-2d8882e2891f

	/// Number of spendable loyalty points that are not spent in the Points Store, but are removed for some reason, e.g. points pass expiration date, or a points correction
	measure 'Loyalty Points Lost' =
			CALCULATE(
			    [All Loyalty Points],
			    ISBLANK('Loyalty Point Measures'[loyalty_order_id]) && 'Loyalty Point Measures'[Transaction Points] < 0
			)
		formatString: #,0
		isHidden
		lineageTag: 869635da-16d5-459a-a046-69e7fdf8f3b1

	/// Number of loyalty points that have not expired but are yet to be spent
	measure 'Loyalty Points Remaining' = 
			CALCULATE(
				SUM('Loyalty Point Measures'[Remaining Points])
			)
		formatString: #,0
		isHidden
		lineageTag: loyalty-points-remaining

	/// Number of spendable points earned from a level boost. These are only earned on Mealboxes orders. Orders for gift cards are not included. 
	measure 'Points from Level Boost' = 
			CALCULATE(
				SUM('Loyalty Point Measures'[Level Booster Points])
			)
		formatString: #,0
		isHidden
		lineageTag: points-from-level-boost

	/// Number of spendable points earned from a Gold level boost. These are only earned on Mealboxes orders. Orders for gift cards are not included. 
	measure 'Points from Gold Level Boost' = 
			CALCULATE(
				[Points from Level Boost],
				'Loyalty Point Measures'[loyalty_level_number] = 4
			)
		formatString: #,0
		isHidden
		lineageTag: points-from-gold-boost

	/// Number of spendable points earned from a level boost. These are only earned on Mealboxes orders. Orders for gift cards are not included. 
	measure 'Points from Silver Level Boost' = 
			CALCULATE(
				[Points from Level Boost],
				'Loyalty Point Measures'[loyalty_level_number] = 3
			)
		formatString: #,0
		isHidden
		lineageTag: points-from-silver-boost

	column 'Level Booster Points'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: level_booster_points
	
	column loyalty_level_number
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: loyalty_level_number

	column loyalty_points_parent_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: a56d0906-20e8-4f4a-9c77-3affd48b1918
		summarizeBy: none
		sourceColumn: loyalty_points_parent_id

	column loyalty_order_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 3ee0ab08-2c90-4d5f-8807-084daa7f8956
		summarizeBy: none
		sourceColumn: loyalty_order_id

	/// Comments for awarding or removing loyalty points. Usually null or a generic name unless used by Customer Service.
	column 'Transaction Reason'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: e4a8d873-ff57-4eb3-8221-c466d60e9daf
		summarizeBy: none
		sourceColumn: transaction_reason

	/// Loyalty Points earned, spent or expired on this transaction.
	column 'Transaction Points'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c4e636fe-3586-45ff-a1d5-ea52f4ebf3ec
		summarizeBy: none
		sourceColumn: transaction_points

	/// Points remaining from points earned on the parent transaction as of now.
	column 'Remaining Points'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 33a6120f-3960-40d2-b45c-96ebaa4dcdda
		summarizeBy: none
		sourceColumn: remaining_points

	/// ID of the order if points were earned at order generation.
	column billing_agreement_order_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: d4964cde-de1e-4020-8492-53e75058a26f
		summarizeBy: none
		sourceColumn: billing_agreement_order_id

	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 02f5d5eb-a3f2-406e-b95d-5f9efbfa1ae6
		summarizeBy: none
		sourceColumn: company_id

	column 'Source Created At'
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		lineageTag: ca804d29-87c4-4694-82bb-4bb671999359
		summarizeBy: none
		sourceColumn: source_created_at

	column 'Points Expiration Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		lineageTag: b36473d3-b068-458f-a204-e6e3085812bc
		summarizeBy: none
		sourceColumn: points_expiration_date

	column fk_dim_billing_agreements
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: c6230a4b-f366-49b4-a5d6-a0bf7e48e6b4
		summarizeBy: none
		sourceColumn: fk_dim_billing_agreements

	/// Primary key for the preference combinations dimension.
	column fk_dim_preference_combinations
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: fk_dim_preference_combinations

	column fk_dim_loyalty_events
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: fa2e27fa-0bbe-4269-a638-2a3a07c78a96
		summarizeBy: none
		sourceColumn: fk_dim_loyalty_events

	column fk_dim_dates_transaction
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 87fb4610-e6b7-45cb-b131-b31cf0f8d3d5
		summarizeBy: none
		sourceColumn: fk_dim_dates_transaction

	column fk_dim_dates_points_expiration
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: cab55d7f-6da7-49b2-979b-2a3aeb61119d
		summarizeBy: none
		sourceColumn: fk_dim_dates_points_expiration

	column fk_dim_companies
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 2da3bd8c-da9a-4562-8b60-681b44cd5709
		summarizeBy: none
		sourceColumn: fk_dim_companies

	column fk_dim_loyalty_seasons
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 45ba48b3-c769-430b-9991-82e95f634b26
		summarizeBy: none
		sourceColumn: fk_dim_loyalty_seasons

	partition 'Loyalty Point Measures' = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    fact_loyalty_points_Table = gold_Schema{[Name="fact_loyalty_points",Kind="Table"]}[Data]
				in
				    fact_loyalty_points_Table
