table 'Menu Measures'
	lineageTag: 007c46b4-40eb-4dda-b8d8-38aff56cc4ff

	/// The number of unique recipes in the menu (not to be confused with main recipes)
	measure 'Number of Recipes in Menu' = DISTINCTCOUNTNOBLANK('Menu Measures'[recipe_id])
		formatString: #,0
		lineageTag: aa718a65-cb1e-4b91-8c98-f185b10bf852

	/// The number of unique menu ids.
	measure 'Number of Menus' = DISTINCTCOUNTNOBLANK('Menu Measures'[menu_id])
		formatString: #,0
		isHidden
		lineageTag: 1f670f36-e0c8-4565-acf8-ba11a315573d

	/// The average value of the rating score.
	/// The rating score is the original rating 1-5 recalculated to a 0-100 scale.
	measure 'Average Recipe Rating Score' =
			CALCULATE(
				AVERAGE('Order Measures'[Recipe Rating Score])
				)
		formatString: 0.0
		lineageTag: dc8be7f2-eb6c-4959-84f1-088adf406654
		displayFolder: Recipe Ratings

	/// The number of unique comments posted.
	/// A unique comments means one customer commenting on one recipe.
	/// Even if the actual text is the same it will count as different if the customer or the recipe is different.
	measure 'Number of Recipe Comments' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[Recipe Comment Id])
				)
		formatString: #,0
		lineageTag: bc6fcdf9-e3b7-431c-b52f-47695eb1dd7e
		displayFolder: Recipe Ratings

	/// The number of unique comments divided by the total number of dishes.
	/// The purpose of this measure is to be able to compare the number of comments between weeks when the number of dishes ordered varies.
	/// When more dishes are sold there will generally be more comments.
	measure 'Share of Ordered Dishes with Comment' =
			CALCULATE(
				[Number of Recipe Comments] / [Number of Ordered Dishes]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 54e62f69-6bfa-4999-a6e9-2ad5846b25f0
		displayFolder: Recipe Ratings

	/// The number of unique customers posting a rating.
	/// Customers marking "dish not cooked" are included.
	measure 'Number of Rating Customers' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[billing_agreement_id])
					, 'Order Measures'[Recipe Rating Id] <> BLANK()
				)
		formatString: #,0
		lineageTag: 370a5c81-d627-4103-9363-0f25903eeeb0
		displayFolder: Recipe Ratings

	/// The number of unique customer posting a rating divided by the total number of orders.
	/// Customers marking "dish not cooked" are included.
	/// The purpose of this measure is to be able to compare the number of customers posting a rating between weeks when the number of ordering customers varies.
	/// When more customers are ordering the number of customers posting a rating will also be higher.
	measure 'Share of Ordering Customers with Dish Rating' =
			CALCULATE(
				[Number of Rating Customers] / [Number of Ordering Customers]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 30040681-4c5e-4a2f-88eb-7648269b6b95
		displayFolder: Recipe Ratings

	/// The number of dishes marked as "dish not cooked".
	/// Counts as unique with every customer marking each dish.
	/// Two customers marking the same dish as "not cooked" will count as 2.
	measure 'Number of Dishes Not Cooked' =
			CALCULATE(
				DISTINCTCOUNT('Order Measures'[Recipe Rating Id])
					, 'Order Measures'[is_not_cooked_dish] = TRUE()
				)+0
		formatString: 0
		lineageTag: ca52eb56-1016-4b87-b59c-4804b629d3ef
		displayFolder: Recipe Ratings

	/// The number of dishes marked as "dish not cooked" divided by the total number of ratings.
	/// The purpose of this measure is to be able to compare the number of dishes not cooked between weeks when the number of ratings varies.
	/// When the general attention to rating dishes is lower the number of dishes marked as not cooked will also be lower.
	measure 'Share of Rated Dishes not Cooked' =
			CALCULATE(
				[Number of Dishes Not Cooked] / [Number of Ratings]
				)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 39c7a96b-50ad-446b-a6b9-d5ea1670e2a2
		displayFolder: Recipe Ratings

	/// The number of unique ratings posted. A unique rating is the rating of one dish by one customer.
	/// If one customer rates 3 dishes and another rates 2 dishes, then these are 5 unique ratings regardless of which specific dishes they rated.
	/// Dish not cooked is excluded.
	measure 'Number of Ratings' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[Recipe Rating Id])
					, 'Order Measures'[is_not_cooked_dish] = FALSE()
				)
		formatString: #,0
		lineageTag: c056ab91-83d4-4db3-aa8d-fb27ac10e9c2
		displayFolder: Recipe Ratings

	/// The number of unique ratings posted divided by the total number of dishes sold.
	/// The purpose of this measure is to be able to compare the number of ratings between weeks when the number of dishes sold varies.
	/// If fewer dishes are sold the number of ratings will also be lower.
	measure 'Share of Ordered Dishes with Rating' =
			CALCULATE(
				[Number of Ratings] / [Number of Ordered Dishes]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bc329d84-dd32-46c0-9dd6-21157b306135
		displayFolder: Recipe Ratings

	/// The number of unique recipes that have received any rating.
	/// Dish not cooked is excluded.
	measure 'Number of Recipes with Rating' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[recipe_id])
					, 'Order Measures'[Recipe Rating Id] <> BLANK()
					, 'Order Measures'[is_not_cooked_dish] = FALSE()
				)
		formatString: #,0
		lineageTag: 27195082-227f-4e26-8144-68af06a5c82b
		displayFolder: Recipe Ratings

	column weekly_menu_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 87bba871-32d9-402a-9600-49f3bcdeb8f4
		summarizeBy: sum
		sourceColumn: weekly_menu_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column menu_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 49f2a2a1-76cf-4d75-a746-76a243bef515
		summarizeBy: sum
		sourceColumn: menu_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column recipe_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: bd5730d4-82e2-43a2-94df-67d3e0bdda45
		summarizeBy: sum
		sourceColumn: recipe_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column portion_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 7cfd0814-ebf2-4ab4-b49b-b298e8ecdad4
		summarizeBy: sum
		sourceColumn: portion_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column portion_quantity
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: bd336b8a-e970-4983-9843-81cefd77bdb3
		summarizeBy: sum
		sourceColumn: portion_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_recipes
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 6b67936c-2eb6-4a73-8cae-d1d3d15320df
		summarizeBy: none
		sourceColumn: fk_dim_recipes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_date
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3a2fe65b-2943-4dbc-bf84-f0292bd6183a
		summarizeBy: none
		sourceColumn: fk_dim_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_companies
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1b4be08f-b320-4b37-b560-5cb387b73139
		summarizeBy: none
		sourceColumn: fk_dim_companies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pk_fact_menus
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1ed8ab09-dc2b-476d-be4a-bd325747dcc8
		summarizeBy: none
		sourceColumn: pk_fact_menus

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: f4f1f340-16fd-4179-8637-046bba14ff83
		summarizeBy: none
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	column product_variation_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 67682412-4cef-484f-8d46-5a195726629e
		summarizeBy: none
		sourceColumn: product_variation_id

		annotation SummarizationSetBy = Automatic

	column menu_recipe_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 5974aec6-df70-407c-8ae2-1efbbd68884c
		summarizeBy: sum
		sourceColumn: menu_recipe_id

		annotation SummarizationSetBy = Automatic

	column recipe_portion_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: bcc28c3d-0fc4-4a3f-9e51-e79a20d0ea9e
		summarizeBy: sum
		sourceColumn: recipe_portion_id

		annotation SummarizationSetBy = Automatic

	column menu_year
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: f6705598-0c5e-4dff-a29c-42e91f495981
		summarizeBy: sum
		sourceColumn: menu_year

		annotation SummarizationSetBy = Automatic

	column menu_week
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 8f39ea6f-011c-4fa3-b76e-e86f89d9571b
		summarizeBy: sum
		sourceColumn: menu_week

		annotation SummarizationSetBy = Automatic

	column menu_week_monday_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		isAvailableInMdx: false
		lineageTag: b8629559-5ffc-4f8e-81a8-68b8824d7ce0
		summarizeBy: none
		sourceColumn: menu_week_monday_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column menu_number_days
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: dccf110d-d008-40db-a269-749d43cc33da
		summarizeBy: sum
		sourceColumn: menu_number_days

		annotation SummarizationSetBy = Automatic

	column menu_recipe_order
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 36b478e8-619b-40b8-9a37-ff72e8d2defa
		summarizeBy: sum
		sourceColumn: menu_recipe_order

		annotation SummarizationSetBy = Automatic

	column fk_dim_products
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: ed5ba6b8-3550-4f26-ad71-99a443706e58
		summarizeBy: none
		sourceColumn: fk_dim_products

		annotation SummarizationSetBy = Automatic

	column fk_dim_portions
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: fk_dim_portions

	column is_dish
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: 715a6e6f-0a07-45b7-9e19-4d3664060e7e
		summarizeBy: none
		sourceColumn: is_dish

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column has_menu_recipes
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: b8611432-9d98-4047-9746-7e14ff0aba77
		summarizeBy: none
		sourceColumn: has_menu_recipes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column has_recipe_portions
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: d648721a-64d1-4cb9-b7db-2b29b37aa872
		summarizeBy: none
		sourceColumn: has_recipe_portions

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_artificial_week
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1873f07a-e127-4f1a-9b02-5bc047abbbb5
		summarizeBy: none
		sourceColumn: is_artificial_week

		annotation SummarizationSetBy = Automatic

	column portion_name
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1d7fcaaf-803a-47b5-9352-22f10ca0b149
		summarizeBy: none
		sourceColumn: portion_name

		annotation SummarizationSetBy = Automatic

	partition 'Menu Measures' = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    fact_menus_Table = gold_Schema{[Name="fact_menus",Kind="Table"]}[Data]
				in
				    fact_menus_Table

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation
