table 'Order Measures'
	lineageTag: 6c298811-8ad5-482b-b89a-827db89210a3

	/// MEASURES ///
	/// Total order value excluding vat
	measure 'Total Order Value Ex Vat' =
			
			CALCULATE(
			    SUM('Order Measures'[total_amount_ex_vat]),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			
			)
		isHidden
		lineageTag: 9514c3b0-8d1c-49a4-a547-99ac13fa089d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}


	/// Order value including VAT
	measure 'Total Order Value Inc Vat' =
			
			CALCULATE(
			    SUM('Order Measures'[total_amount_inc_vat]),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		isHidden
		lineageTag: 5cba6729-7b7c-48ce-9c67-e695bff2c63a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of orders
	measure 'Number of Orders' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[billing_agreement_order_id]),
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		lineageTag: d7731cff-64d8-45f8-ad92-7833eb7a22e9
	
	/// The number of customers with an order
	measure 'Number of Ordering Customers' =
			CALCULATE(
				DISTINCTCOUNTNOBLANK('Order Measures'[billing_agreement_id]),
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				USERELATIONSHIP(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
					'Billing Agreements Deviation'[pk_dim_billing_agreements]
				),
				USERELATIONSHIP(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
					'Billing Agreements Deviation'[pk_dim_billing_agreements]
				),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
					'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
					'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
	
	/// Average number of orders per unique customers placing an order in the selected filtering context (i.e. time, preferences etc.)
	measure 'Average Number of Orders per Customer' = DIVIDE(['Number of Orders'], ['Number of Ordering Customers'], BLANK())
		formatString: #,0.00

	/// Number of order that has one or more grocery purchases
	measure 'Number of Orders with Groceries' = CALCULATE([Number of Orders], Products[Product Type Name] IN {"Standalone-groceries", "Add-on-product"})
		formatString: #,0
		displayFolder: Groceries
	
	/// Percentage of orders that contains groceries
	measure 'Share of Orders with Groceries' = DIVIDE([Number of Orders with Groceries],[Number of Orders], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Groceries
	
	/// Revenue from groceries of completed orders
	/// Excluding VAT
	measure 'Grocery Value Ex Vat' = CALCULATE([Order Value Gross Ex Vat], Products[Product Type Name] IN {"Standalone-groceries", "Add-on-product"})
		formatString: #,0
		displayFolder: Groceries

	/// Average grocery revenue per completed order with groceries
	/// Excluding VAT
	measure 'ATV of Groceries Ex Vat' = DIVIDE([Grocery Value Ex Vat],[Number of Orders with Groceries], BLANK())
		formatString: #,0.00
		displayFolder: Groceries
		
	/// Average order value
	/// Excluding VAT
	/// Before unhiding: Why are some order statuses excluded for number of orders but not here?
	measure 'Average Order Value Ex Vat' = DIVIDE([Total Order Value Ex Vat],[Number of Orders],BLANK())
		lineageTag: 85357b8f-6a82-4a0a-8243-d2756573a1b2
		isHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average order value
	/// Including VAT
	/// Before unhiding: Why are some order statuses excluded for number of orders but not here?
	measure 'Average Order Value Inc Vat' = DIVIDE([Total Order Value Inc Vat],[Number of Orders],BLANK())
		lineageTag: e35a4577-2ae2-46b4-8511-031e29d678ec
		isHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of orders where the customers order included a printed recipe leaflet.
	measure 'Number of Orders with Recipe Leaflet' = CALCULATE([Number of Orders], 'Order Measures'[has_recipe_leaflets] = TRUE())
		formatString: #,0
		lineageTag: cf598a2d-2b0e-4370-959f-3d0dab5bbcec

	/// Sum of Product Variation Quantity
	measure 'Product Variation Quantity' =
			
			CALCULATE(
			    SUM('Order Measures'[product_variation_quantity]),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		isHidden
		lineageTag: 6da36c65-3977-4355-9613-98ce2076a5ba

		changedProperty = IsHidden

	/// Average price per unit
	/// Including VAT
	/// Example: A person bought 2 cucumbers, 1 milk and 1 apple. If we want to 
	/// know the average price paid per grocery item. This would give you the
	/// order value divided by 4 (number of products)
	measure 'Average Unit Price Inc Vat' = DIVIDE([Total Order Value Inc Vat],[Number of Ordered Units])
		lineageTag: 01e8c74d-66dd-4082-bcee-a4c91dcc5c76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average price per unit
	/// Excluding VAT
	measure 'Average Unit Price Ex Vat' = DIVIDE([Total Order Value Ex Vat],[Number of Ordered Units])
		lineageTag: 461d3a40-d20c-45d2-aa78-46a36a2ce6ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of sold gift cards
	measure 'Number of Sold Gift Cards' =
			CALCULATE(
				[Number of Orders],
				'Order Types'[Order Type Name] = "Gift Card",
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"}
			)
		formatString: #,0
		lineageTag: 1b7a5c95-92ad-44ef-b403-00fd4b24f4af

	/// Total net order value
	/// Excluding VAT
	measure 'Order Value Net Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring","Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"}
				)
		lineageTag: 94703f73-cb72-4c7c-ba82-9d480c9385ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}
	
	/// Net order value
	/// Including VAT
	measure 'Order Value Net Inc Vat' =
			CALCULATE(
				[Total Order Value Inc Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"}
				)
		lineageTag: 47be5d17-2f0a-42c6-8b21-24dea811838e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Gross order value
	/// Excluding VAT
	measure 'Order Value Gross Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				'Order Measures'[order_line_type_name] IN {"DEBIT", "TRANSPORT"}
				)
		lineageTag: 9db412c4-2ea6-4c39-81b2-c68ec727df34

		annotation PBI_FormatHint = {"isGeneralNumber":true}
	
	/// Average net order value 
	/// Excluding VAT
	measure 'Average Order Value Net Ex Vat' = DIVIDE([Order Value Net Ex Vat],[Number of Orders],BLANK())
		lineageTag: 69286001-d4af-4316-bc1d-20e7ae3e405b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average gross order value
	/// Excluding VAT
	measure 'Average Order Value Gross Ex Vat' = DIVIDE([Order Value Gross Ex Vat],[Number of Orders],BLANK())
		lineageTag: c678f208-e305-4ff1-997e-b5da8a25f094

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average net order value
	/// Including VAT
	measure 'Average Order Value Net Inc Vat' = DIVIDE([Order Value Net Inc Vat],[Number of Orders],BLANK())
		lineageTag: 935be5ed-4ed8-47d6-96b3-433c36ba087e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of total quantity by product variation
	measure 'Number of Ordered Units' =
			CALCULATE(
				[Product Variation Quantity],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"}
			)
		formatString: #,0
		lineageTag: ffd7948c-ef03-4234-b6e8-94515eca77eb

	/// Sum of value of gift card
	/// Excluding VAT
	measure 'Gift Card Value Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] = "Gift Card",
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"}
			)
		lineageTag: 871b6c01-d9c2-4f61-a597-80dd7b6d6c3b
		isHidden
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of discount value
	/// Excluding VAT
	measure 'Discount Value Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				'Order Measures'[order_line_type_name] IN {"DISCOUNT"}
			)
		lineageTag: a27fd9f8-407b-49fb-bdee-29f4121fffd5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of Transport value
	/// Excluding VAT
	measure 'Transport Value Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				'Order Measures'[order_line_type_name] IN {"TRANSPORT"}
			)
		lineageTag: eb52e954-e781-4d81-b8e0-87f5effaf6ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of PRP (credit related to order) value
	/// Excluding VAT	
	measure 'Sum PRP Value Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				'Order Measures'[order_line_type_name] IN {"PRP"}
			)
		lineageTag: 7ca94156-13fd-4a37-9c34-0417bc4e5819

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of credit value
	/// Excluding VAT		
	measure 'Credit Value Ex Vat' =
			CALCULATE(
				[Total Order Value Ex Vat],
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				'Order Measures'[order_line_type_name] IN {"Credit"}
			)
		lineageTag: 1fe11954-5b54-4c34-9abb-796297d4ecee

		annotation PBI_FormatHint = {"isGeneralNumber":true}
	
	/// Number of dishes which the customer replaced with another dish.
	/// NOTE: This measure can only be used on a mealbox level, not in dish level.
	/// If you're interested in information on dishes (such as number of dishes removed with ingredient X), 
	/// use the measures for Number of added/removed dishes
	measure 'Number of Swapped Dishes' =
			
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            [Number of Removed Dishes] - [Decreased Meals]
			        )
			)
		formatString: #,0
		lineageTag: 123f1862-185e-49e7-9891-ad2bdd843d29

	/// Number of dishes which the customer replaced a preselector dish with
	/// NOTE: This measure can only be used on a mealbox level, not in dish level.
	/// If you're interested in information on dishes (such as number of dishes removed with ingredient X), 
	/// use the measures for Number of added/removed dishes
	measure 'Number of Swapped In Dishes' =
			
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            [Number of Added Dishes] - [Increased Meals]
			        )
			)
		formatString: #,0
		lineageTag: 0a4fb450-86c8-4c98-9071-470e3602a74a
		isHidden

	/// Number of dishes that have been ordered by the customers	
	measure 'Number of Ordered Dishes' =
			CALCULATE(
				COUNTROWS('Order Measures'),
				'Order Measures'[is_dish] = TRUE(),
				'Order Measures'[fk_dim_recipes] <> "0",
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
			    USERELATIONSHIP(
			        'Order Measures'[fk_dim_billing_agreements_deviations],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		lineageTag: 486a2e72-e1d4-4b82-ab70-9e235c2450b0

	/// Number of dishes added by curtomer
	/// Includes all dishes which the customer has selected themselves 
	/// which were not in the original weekly menu selected for them.
	measure 'Number of Added Dishes' =
			CALCULATE(
				SUM('Order Measures'[is_added_dish]),
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
			    USERELATIONSHIP(
			        'Order Measures'[fk_dim_billing_agreements_deviations],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		lineageTag: 7919afdd-0322-4085-9960-441805140e39

	/// Number of dishes removed.
	/// Includes all dishes in the original weekly menu which the customer has chosen to remove.
	measure 'Number of Removed Dishes' =
			CALCULATE(
					SUM('Order Measures'[is_removed_dish]),
					'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
					'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
					USERELATIONSHIP(
						'Order Measures'[fk_dim_recipes_preselected],
						Recipes[pk_dim_recipes]
					),
					USERELATIONSHIP(
						'Order Measures'[fk_dim_products_preselected],
						Products[pk_dim_products]
					),
				   USERELATIONSHIP(
					   'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
					   'Billing Agreements Deviation'[pk_dim_billing_agreements]
				   ),
				   USERELATIONSHIP(
					   'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
					   'Billing Agreements Deviation'[pk_dim_billing_agreements]
				   ),
				   CROSSFILTER(
					   'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
					   'Billing Agreements'[pk_dim_billing_agreements],
					   None
				   ),
				   CROSSFILTER(
					   'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
					   'Billing Agreements'[pk_dim_billing_agreements],
					   None
				   )
			)
		formatString: #,0
		lineageTag: cb37e06d-5904-49ec-a217-63c87693121e

	/// Share of dishes in order which the customer replaced with other dishes
	/// NOTE: If a dish is removed but not replaced with another dish, it will not be counted.
	measure 'Share of Swapped Dishes' =
			DIVIDE(
				[Number of Swapped Dishes],
				[Number of Preselected Dishes],
				BLANK()
				)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 729d9abc-e5b6-4544-9d9b-a18928e0fea4

	/// Number of dishes initially presented to customer
	measure 'Number of Preselected Dishes' = ```
			CALCULATE(
				COUNTROWS('Order Measures'),
				'Order Measures'[is_dish] = TRUE(),
				'Order Measures'[fk_dim_recipes_preselected] <> "0",
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				USERELATIONSHIP(
					'Order Measures'[fk_dim_recipes_preselected],
					Recipes[pk_dim_recipes]
				),
				USERELATIONSHIP(
					'Order Measures'[fk_dim_products_preselected],
					Products[pk_dim_products]),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
			
			```
		formatString: #,0
		lineageTag: a3d84168-264b-4b04-a9d4-7d0a907ff9c4
		isHidden

	/// Number of orders where the customer replaced one or more dishes with another dish
	measure 'Number of Orders with Swaps' = ```
			
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            CALCULATE(
			                [Number of Orders], 
			                'Order Measures'[is_removed_dish] = 1 || 'Order Measures'[is_added_dish] = 1
			            )
			        )
			)
			```
		formatString: #,0
		lineageTag: 9ec0b504-6ea1-434c-b20f-ab0bbda0e514

	/// Share of orders where the customer replaced one or more dishes with another dish
	measure 'Share of Orders with Swaps' = ```
			
			    DIVIDE(
			        [Number of Orders with Swaps],
			        [Number of Orders],
			        BLANK()
			    )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 77799e35-5f8a-4e3d-a9de-01da07f747f5

	/// Average number of orders where a customer swapped one or more dishes
	measure 'Average Number of Swaps per Order' = ```
			
			    DIVIDE(
			        [Number of Swapped Dishes],
			        [Number of Orders],
			        BLANK()
			    )
			```
		lineageTag: 7a742dc2-ed19-4712-92c9-da29eefc46f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of orders where the customer increased the number of portions
	measure 'Number of Orders with Increased Portions' =
			
			IF(
			    ISFILTERED('Recipes'),
			    BLANK(),
			    IF(
			        ISFILTERED('Products'),
			        BLANK(),
			        CALCULATE(
			            [Number of Orders],
			            'Order Measures'[portion_adjustment_subscription] > 0
			        )
			    )
			)
		formatString: #,0
		lineageTag: 5e7e9802-6556-4d43-b74b-0701d3278f0a

	/// Number of orders where the customer decreased the number of portions
	measure 'Number of Orders with Decreased Portions' =
			
			IF(
			    ISFILTERED('Recipes'),
			    BLANK(),
			    IF(
			        ISFILTERED('Products'),
			        BLANK(),
			        CALCULATE(
			            [Number of Orders],
			            'Order Measures'[portion_adjustment_subscription] < 0
			        )
			    )
			)
		formatString: #,0
		lineageTag: 38061b22-a5c0-44bd-a0ba-095086ce5d51

	/// Number of orders where the customer changed (increased/decreased) the number of portions
	measure 'Number of Orders with Adjusted Portions' =
			
			IF(
			    ISFILTERED('Recipes'),
			    BLANK(),
			    IF(
			        ISFILTERED('Products'),
			        BLANK(),
			        CALCULATE(
			            [Number of Orders],
			            'Order Measures'[portion_adjustment_subscription] <> 0
			        )
			    )
			)
		formatString: #,0
		lineageTag: 85934d19-b088-47ba-8245-938d92c6aced

	/// Number of orders where the customer increased the number of meals/days
	measure 'Number of Orders with Increased Meals' =
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            CALCULATE(
			                [Number of Orders],
			                'Order Measures'[meal_adjustment_subscription] > 0
			            )
			        )
			)
		formatString: #,0
		lineageTag: e552ea0e-69a2-414e-9bd0-219e0b09dc5c

	/// Number of orders where the customer decreased the number of meals/days
	measure 'Number of Orders with Decreased Meals' =
			
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            CALCULATE(
			                [Number of Orders],
			                'Order Measures'[meal_adjustment_subscription] < 0
			            )
			        )
			)
		formatString: #,0
		lineageTag: 9491093b-37d6-4667-829a-9b23c9acc654

	/// Number of orders where the customer adjusted (increased/decreased) the number of meals/days	
	measure 'Number of Orders with Adjusted Meals' =
			
			IF(
			    ISFILTERED('Recipes'),
			        BLANK(),
			        IF(
			            ISFILTERED('Products'),
			            BLANK(),
			            CALCULATE(
			                [Number of Orders],
			                'Order Measures'[meal_adjustment_subscription] <> 0
			            )
			        )
			)
		formatString: #,0
		lineageTag: d8c66ffe-9918-408e-a136-7dfb405fb633

	/// Size of dish adjustment
	/// Shows the "net" dish adjustment, meaning the total adjustment made after adding/removing dishes
	/// Example: A customer removes 3 dishes and adds 2 new dishes. The adjustment size is = -1
	measure 'Difference Added vs Removed Dishes' = [Number of Added Dishes] - [Number of Removed Dishes]
		formatString: #,0
		lineageTag: 1bc0e052-4f0d-4564-8dcc-cefb9ba5604c

	/// Middle step calculation used to find the difference between orderes meals and subscribed meals
	measure 'Meal Adjustments' =
			
			CALCULATE(
			    IF(
			        ISFILTERED('Recipes'),
			            BLANK(),
			            IF(
			                ISFILTERED('Products'),
			                BLANK(),
			                CALCULATE(
			    	            SUM('Order Measures'[meal_adjustment_subscription]),
			    	            'Order Types'[Order Type Name] IN {"Recurring",     "Order After Registration", "Orders After Cutoff",  "Daily Direct Order",    "Campaign"},
			    	            'Order Statuses'[Order Status Name] IN {"Finished",     "Processing"}
			                )
			            )
			    ),
			    USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		isHidden
		lineageTag: 15fc3c41-f4e7-455c-8502-cfb16f3a92db

	/// Middle step calculation used to find swapped dishes
	measure 'Decreased Meals' =
			CALCULATE(
				[Meal Adjustments],
				'Order Measures'[meal_adjustment_subscription] < 0
			
			)
			
		formatString: #,0
		isHidden
		lineageTag: 72548e83-a743-498b-90e6-d199251b894f

	/// Middle step calculation used to find swapped dishes
	measure 'Increased Meals' =
			CALCULATE(
				[Meal Adjustments],
				'Order Measures'[meal_adjustment_subscription] > 0
			
			)
		formatString: #,0
		isHidden
		lineageTag: 721b6dae-e435-404d-b057-75831058d524

	/// Difference between ordered portions and subscribed portions
	measure 'Portion Adjustments' =
			CALCULATE(
				SUM('Order Measures'[portion_adjustment_subscription]),
				'Order Types'[Order Type Name] IN {"Recurring", "Order After Registration", "Orders After Cutoff", "Daily Direct Order", "Campaign"},
				'Order Statuses'[Order Status Name] IN {"Finished", "Processing"},
				USERELATIONSHIP(
			        'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				USERELATIONSHIP(
			        'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements Deviation'[pk_dim_billing_agreements]
			    ),
				CROSSFILTER(
					'Bridge Billing Agreements Preferences'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				),
				CROSSFILTER(
					'Bridge Billing Agreements Subscribed Products'[fk_dim_billing_agreements],
			        'Billing Agreements'[pk_dim_billing_agreements],
					None
				)
			)
		formatString: #,0
		isHidden
		lineageTag: acb06567-e631-49f7-9d41-40399ca3d51f
	
	/// Mostly a middle step measure.
	/// Nice to have for % of grand total calculations
	measure 'Number of Orders All Recipes' =
			CALCULATE(
				[Number of Orders],
				ALL(Recipes)
			)
		formatString: #,0
		isHidden
		lineageTag: 375ab208-b385-4455-9b5e-9e7dc70606ae

	column order_status_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 97d4bcb3-e53a-4277-af57-57a94757ec39
		summarizeBy: none
		sourceColumn: order_status_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_type_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 094f462a-d367-48ec-9a45-4eeba1a9b353
		summarizeBy: none
		sourceColumn: order_type_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column billing_agreement_order_line_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 0319b8db-e0ea-4266-98d5-4460f2f2825a
		summarizeBy: none
		sourceColumn: billing_agreement_order_line_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_variation_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 64dfca24-3043-4e81-a204-f255f0399874
		summarizeBy: none
		sourceColumn: product_variation_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_line_type_name
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 6093c33b-13e6-4718-84fa-0caeafa121df
		summarizeBy: none
		sourceColumn: order_line_type_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column vat
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 4521f41d-a9a8-484a-9159-d4046240c6ea
		summarizeBy: sum
		sourceColumn: vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_price_ex_vat
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 7f9d2ac1-3639-4135-b1dd-80415012e217
		summarizeBy: sum
		sourceColumn: unit_price_ex_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_price_inc_vat
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 97dc1a98-b450-4c70-b648-52f8b8697a06
		summarizeBy: sum
		sourceColumn: unit_price_inc_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_amount_ex_vat
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 08f563d8-4a6b-42f1-a6a2-defc5b017a7f
		summarizeBy: sum
		sourceColumn: total_amount_ex_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_amount_inc_vat
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 7d29bced-8264-4b7b-ad97-48e24fed616a
		summarizeBy: sum
		sourceColumn: total_amount_inc_vat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_delivery
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: 61ef0da3-7497-4720-a9b7-cc7bffba031a
		summarizeBy: none
		sourceColumn: has_delivery

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column has_recipe_leaflets
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: ae54f7b9-96c6-45c6-8350-728a3cb4e046
		summarizeBy: none
		sourceColumn: has_recipe_leaflets

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column menu_week_monday_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		isAvailableInMdx: false
		lineageTag: 62dff093-e3e8-4176-8b77-39772f786b2f
		summarizeBy: none
		sourceColumn: menu_week_monday_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fk_dim_order_types
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5433926e-8415-406d-bcf6-50d345c90dc2
		summarizeBy: none
		sourceColumn: fk_dim_order_types

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_products
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 272a1795-5763-4cfd-9ac3-330f7a344bf8
		summarizeBy: none
		sourceColumn: fk_dim_products

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_billing_agreements_ordergen
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 0becfd8d-060a-46cc-8f99-831e7bb3c105
		summarizeBy: none
		sourceColumn: fk_dim_billing_agreements_ordergen

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_companies
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 791ace8d-5c19-4331-ae91-56c97085cfc2
		summarizeBy: none
		sourceColumn: fk_dim_companies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_date
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3f4a1497-0525-4d8c-8938-ad437ac4ef2c
		summarizeBy: none
		sourceColumn: fk_dim_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column billing_agreement_order_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 70d325d5-6b5b-4424-b033-e2139b7ba9d6
		summarizeBy: none
		sourceColumn: billing_agreement_order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column billing_agreement_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 84439a3d-2be2-48be-964d-7db562b16e3e
		summarizeBy: sum
		sourceColumn: billing_agreement_id

		annotation SummarizationSetBy = Automatic

	column product_variation_quantity
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: b613ba0a-475c-451f-bff3-3cfd47ff7e11
		summarizeBy: sum
		sourceColumn: product_variation_quantity

		annotation SummarizationSetBy = Automatic

	column source_created_at
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		lineageTag: e99eabef-0f79-4460-9922-2e36345a8b12
		summarizeBy: none
		sourceColumn: source_created_at

		annotation SummarizationSetBy = Automatic

	column fk_dim_order_statuses
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 60b9f4ea-5ffd-47de-8d2a-ea17152d4334
		summarizeBy: none
		sourceColumn: fk_dim_order_statuses

		annotation SummarizationSetBy = Automatic

	column pk_fact_orders
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: c6046602-8856-4929-b847-3477e9f6da80
		summarizeBy: none
		sourceColumn: pk_fact_orders

		annotation SummarizationSetBy = Automatic

	column menu_year
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c9673c50-5e6f-469e-8554-fbde45b0c193
		summarizeBy: sum
		sourceColumn: menu_year

		annotation SummarizationSetBy = Automatic

	column menu_week
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 97307c94-3a2d-46bf-ba58-454db4d19551
		summarizeBy: sum
		sourceColumn: menu_week

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 2338558b-3049-4416-af88-185958bdc6e8
		summarizeBy: none
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	column fk_dim_products_preselected
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 9ddcb8e7-5e53-41e2-8d8b-69b02321fe10
		summarizeBy: none
		sourceColumn: fk_dim_products_preselected

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_recipes
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 9779d293-0b93-49e8-a958-cf3094e720a4
		summarizeBy: none
		sourceColumn: fk_dim_recipes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_recipes_preselected
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: a83a42fe-d628-44f3-a944-434b8c7c3dab
		summarizeBy: none
		sourceColumn: fk_dim_recipes_preselected

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_added_dish
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c50d60a1-08bf-4219-a72b-aa0adfe53841
		summarizeBy: sum
		sourceColumn: is_added_dish

		annotation SummarizationSetBy = Automatic

	column is_removed_dish
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 0bce8e48-e1a3-4ac5-96a2-0a81a4030231
		summarizeBy: sum
		sourceColumn: is_removed_dish

		annotation SummarizationSetBy = Automatic

	column language_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: dffdd704-34fa-4a27-a9e5-84cd05d151ab
		summarizeBy: sum
		sourceColumn: language_id

		annotation SummarizationSetBy = Automatic

	column is_dish
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: c0037b56-1a60-4707-a64a-e2906f2b493c
		summarizeBy: none
		sourceColumn: is_dish

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ops_order_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5e6494bf-67e2-4018-8da4-312942ab4a6c
		summarizeBy: sum
		sourceColumn: ops_order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column preselected_product_variation_id
		dataType: string
		isHidden
		lineageTag: c1704f19-b63d-43d0-9b42-e651da388077
		summarizeBy: none
		sourceColumn: preselected_product_variation_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column recipe_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0704f8ef-3920-4380-a45a-e07118aaa5c8
		summarizeBy: sum
		sourceColumn: recipe_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column preselected_recipe_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fe464424-3aec-4605-a156-127ea206aee8
		summarizeBy: sum
		sourceColumn: preselected_recipe_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column meal_adjustment_subscription
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9de2f151-76bb-4299-b656-b162975c6d4e
		summarizeBy: sum
		sourceColumn: meal_adjustment_subscription

		changedProperty = IsHidden

	column portion_adjustment_subscription
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 016251e9-4b56-4c8e-9bd0-a5612a033a5a
		summarizeBy: sum
		sourceColumn: portion_adjustment_subscription

		changedProperty = IsHidden

	column 'Recipe Comment'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: recipe_comment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic


	column 'Recipe Rating Score'
		dataType: double
		isHidden
		isAvailableInMdx: false
		summarizeBy: sum
		sourceColumn: recipe_rating_score

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Recipe Rating'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: sum
		sourceColumn: recipe_rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_not_cooked_dish
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: is_not_cooked_dish

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_billing_agreements_deviations
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 70f41c62-2bf4-4d7d-ad49-eb860a3a49c7
		summarizeBy: none
		sourceColumn: fk_dim_billing_agreements_deviations

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_basket_deviation_origins
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: f36e57bf-a06a-4770-b51d-8bfcb3d8dd7d
		summarizeBy: none
		sourceColumn: fk_dim_basket_deviation_origins

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fk_dim_basket_deviation_origins_preselected
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 4c93f8f6-edfd-491e-af59-8152c8992d3d
		summarizeBy: none
		sourceColumn: fk_dim_basket_deviation_origins_preselected

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Recipe Rating Id'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: recipe_rating_id

	column 'Recipe Comment Id'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: recipe_comment_id

	partition 'Order Measures' = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    fact_orders_Table = gold_Schema{[Name="fact_orders",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(fact_orders_Table, each [source_created_at] >= RangeStart and [source_created_at] < RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation