/// A table which contains measures about the preselector output for a subscriber's menu week.
table 'Preselector Measures'
	lineageTag: preselecor-measures-table

    /// The number of mealboxes that have been output by the preselector and have satisfied all the subscriber's taste preferences
    measure 'Number of Mealboxes with Taste Preferences Upheld' =
            CALCULATE(
                [Number of Mealboxes from Preselector],
                'Preselector Details'[Taste Preference Compliancy Code] = 3
                )
        formatString: #,0
        displayFolder: Preference Compliance

    /// The number of mealboxes that have been output by the preselector that have at least one dish that has broken at least one of the subscriber's non-allergy taste preferences (e.g. fish, pork)
    measure 'Number of Mealboxes with Non-Allergy Taste Preferences Broken' =
            CALCULATE(
                [Number of Mealboxes from Preselector],
                    'Preselector Details'[Taste Preference Compliancy Code] = 2
                )
        formatString: #,0
        displayFolder: Preference Compliance

    /// The number of mealboxes that have been output by the preselector that have at least one dish that has broken at least one of the subscriber's allergy taste preferences (e.g. nuts, lactose)
    measure 'Number of Mealboxes with Allergy Taste Preferences Broken' =
            CALCULATE(
                [Number of Mealboxes from Preselector],
                'Preselector Details'[Taste Preference Compliancy Code] = 1
                )
        formatString: #,0
        displayFolder: Preference Compliance

    /// The share of mealboxes that have been output by the preselector that have at least one dish that has broken at least one of the subscriber's allergy or non-allergy taste preferences (e.g. fish, pork, nuts, lactose)
    measure 'Share of Mealboxes with Taste Preferences Broken' =
            CALCULATE(
                ([Number of Mealboxes with Non-Allergy Taste Preferences Broken]
                + [Number of Mealboxes with Allergy Taste Preferences Broken])
                / [Number of Mealboxes from Preselector]
                )
        formatString: 0.00\ %;-0.00\ %;0.00\ %
        displayFolder: Preference Compliance

    /// The number of mealboxes that have been output by the preselector
    measure 'Number of Mealboxes from Preselector' =
            IF(
                OR(ISFILTERED('Recipes'), ISFILTERED('Taxonomies')),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[preselector_output_id]),
                    'Preselector Details'[Is Dish] = TRUE()
                ),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[preselector_output_id]),
                    'Preselector Details'[Is Dish] = FALSE()
                )
            )
        formatString: #,0

    /// The number of dishes that have been output by the preselector
    measure 'Number of Dishes from Preselector' =
            CALCULATE(
                COUNT('Preselector Details'[recipe_id]),
                    'Preselector Details'[Is Dish] = TRUE()
                )
        formatString: #,0

    /// The number of subscribers that have received a preselector output.
    measure 'Number of Subscribers with Preselector Output' =
            IF(
                OR(ISFILTERED('Recipes'), ISFILTERED('Taxonomies')),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[billing_agreement_id]),
                    'Preselector Details'[Is Dish] = TRUE()
                ),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[billing_agreement_id]),
                    'Preselector Details'[Is Dish] = FALSE()
                )
            )
        formatString: #,0

    /// The number of activesubscribers that have received a preselector output.
    measure 'Number of Active Subscribers with Preselector Output' =
            IF(
                OR(ISFILTERED('Recipes'), ISFILTERED('Taxonomies')),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[billing_agreement_id]),
                    'Preselector Details'[Is Dish] = TRUE(),
                    'Customer and Subscriber Details'[Billing Agreement Status] = "Active"
                ),
                CALCULATE(
                    DISTINCTCOUNT('Preselector Details'[billing_agreement_id]),
                    'Preselector Details'[Is Dish] = FALSE(),
                    'Customer and Subscriber Details'[Billing Agreement Status] = "Active"
                )
            )
        formatString: #,0

    /// The overall quality metric (0 bad - 1 good) of the preselector output, calculated as a combination of the rotation and main ingredient variation scores for mealboxes
    measure 'Average Combined Rotation and Variation Score' =
            CALCULATE(
                AVERAGE('Preselector Details'[Combined Rotation Variation Score]),
                    'Preselector Details'[Is Dish] = FALSE()
                )
        formatString: #,0.00
        displayFolder: Selection Quality

    /// The average score (0 bad - 1 good) for how often dishes are repeated for a subscriber
    measure 'Average Rotation Score' =
            IF(
                OR(ISFILTERED('Recipes'), ISFILTERED('Taxonomies')),
                CALCULATE(
                    AVERAGE('Preselector Details'[Rotation Score]),
                    'Preselector Details'[Is Dish] = TRUE()
                    ),
                CALCULATE(
                    AVERAGE('Preselector Details'[Rotation Score]),
                    'Preselector Details'[Is Dish] = FALSE()
                    )
            )
        formatString: #,0.00
        displayFolder: Selection Quality

    /// The average score (0 bad - 1 good) for how much main ingredient variation there is in a mealbox
    measure 'Average Main Ingredient Variation Score' =
            CALCULATE(
                AVERAGE('Preselector Details'[Main Ingredient Variation Score]),
                    'Preselector Details'[Is Dish] = FALSE()
                )
        formatString: #,0.00
        displayFolder: Selection Quality

	/// The sum of the planned recipe cost of the recipes preselected for the customers.
	/// It is the cost used in menu planning, and calculated using the exact quantity of all included ingredients.
	measure 'Recipe Planned Cost from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_planned_cost]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The sum of the planned recipe cost of the recipes preselected for the customers.
	/// It is the cost used in menu planning, and calculated using quantity of all included ingredients, 
	/// where the ingredient quantity is rounded up to the nearest integer (i.e. whole units).
	measure 'Recipe Planned Cost Whole Units from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_planned_cost_whole_units]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The sum of the expected recipe cost of the recipes preselected for the customers.
	/// The expected cost might have a discount that is not to be included in the menu planning process.
	/// This measure is calculated using the exact quantity of all included ingredients.
	measure 'Recipe Expected Cost from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_expected_cost]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The sum of the expected recipe cost of the recipes preselected for the customers.
	/// The expected cost might have a discount that is not to be included in the menu planning process.
	/// This measure is calculated using quantity of all included ingredients, 
	/// where the ingredient quantity is rounded up to the nearest integer (i.e. whole units).
	measure 'Recipe Expected Cost Whole Units from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_expected_cost_whole_units]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The sum of the actual recipe cost of the recipes preselected for the customers.
	/// The actual cost is fetched from the purchasing order(s) for the menu week of the recipe.
	/// This measure is calculated using the exact quantity of all included ingredients.
	measure 'Recipe Actual Cost from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_actual_cost]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The sum of the actual recipe cost of the recipes preselected for the customers.
	/// The actual cost is fetched from the purchasing order(s) for the menu week of the recipe.
	/// This measure is calculated using quantity of all included ingredients, 
	/// where the ingredient quantity is rounded up to the nearest integer (i.e. whole units).
	measure 'Recipe Actual Cost Whole Units from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[total_ingredient_actual_cost_whole_units]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0.00
		displayFolder: Recipe Cost

	/// The total number of plates preselected, which is calculated as the sum of Portions x Meals for all dishes in the selection.
	/// Example: One mealbox with 5 meals and 4 portions per meal will count as 20 servings.
	measure 'Number of Servings from Preselector Output' =
			CALCULATE(
				SUM('Preselector Details'[dish_servings_subscription]),
				'Preselector Details'[Is Dish] = TRUE()
				)
		formatString: #,0

	/// The planned cost per preselected serving.
	/// See [Number of Servings from Preselector] for the definition of servings.
	measure 'Recipe Planned Cost from Preselector Output per Serving' =
			DIVIDE(
				[Recipe Planned Cost from Preselector Output],
				[Number of Servings from Preselector Output],
				BLANK()
			)
		formatString: #,0.00
		displayFolder: Recipe Cost\per Recipe Serving

	/// The expected cost per preselected serving.
	/// See [Number of Servings from Preselector] for the definition of servings.
	measure 'Recipe Expected Cost from Preselector Output per Serving' =
			DIVIDE(
				[Recipe Expected Cost from Preselector Output],
				[Number of Servings from Preselector Output],
				BLANK()
			)
		formatString: #,0.00
		displayFolder: Recipe Cost\per Recipe Serving

	/// The actual cost per preselected serving.
	/// See [Number of Servings from Preselector] for the definition of servings.
	measure 'Recipe Actual Cost from Preselector Output per Serving' =
			DIVIDE(
				[Recipe Actual Cost from Preselector Output],
				[Number of Servings from Preselector Output],
				BLANK()
			)
		formatString: #,0.00
		displayFolder: Recipe Cost\per Recipe Serving

	partition 'Measure Table' = m
		mode: import
		source = GENERATESERIES(1,1,1)
