table Products
	lineageTag: 4ff9201f-5185-4392-bb6c-8c531c115fb3

	column pk_dim_products
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 99ce8f7d-57e2-4cf7-af0e-a358e6be5be9
		summarizeBy: none
		sourceColumn: pk_dim_products

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_concept_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1e1f8cb5-f562-4fc3-afc3-8f7e3515e5c4
		summarizeBy: none
		sourceColumn: product_concept_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_type_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: b1d05b6d-8e2d-4e20-aa4b-054328c3a77c
		summarizeBy: none
		sourceColumn: product_type_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Id'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 00684e75-2ac8-412f-b240-18f569fdb2d4
		summarizeBy: none
		sourceColumn: Product Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_status_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 04095057-51dd-4491-ad06-bf96821a0e4b
		summarizeBy: none
		sourceColumn: product_status_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Variation Id'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 3b8cc03b-c2b2-4495-adbe-1ee758701d04
		summarizeBy: none
		sourceColumn: Product Variation Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 7a4fec61-bb92-4ec5-9b73-f372f0d29c8e
		summarizeBy: none
		sourceColumn: company_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Concept Name'
		dataType: string
		lineageTag: 5a455508-7287-4878-9abd-ca0273bdc011
		summarizeBy: none
		sourceColumn: Product Concept Name

		annotation SummarizationSetBy = Automatic

	column 'Product Type Name'
		dataType: string
		lineageTag: 456bd8d7-d4ac-46e9-b1f6-e96f873ff591
		summarizeBy: none
		sourceColumn: Product Type Name

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: d0e82a8a-e75a-4798-8aa2-8c571e35d25b
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Status Name'
		dataType: string
		lineageTag: d2b6fc73-9a89-4c96-ba32-8a1872086041
		summarizeBy: none
		sourceColumn: Product Status Name

		annotation SummarizationSetBy = Automatic

	column 'Product Variation Name'
		dataType: string
		lineageTag: 08c10034-50aa-4f58-b805-4fb3130f272b
		summarizeBy: none
		sourceColumn: Product Variation Name

		annotation SummarizationSetBy = Automatic

	column Sku
		dataType: string
		lineageTag: 9430db27-2352-43b5-a569-090687009da2
		summarizeBy: none
		sourceColumn: Sku

		annotation SummarizationSetBy = Automatic

	column 'Number of Meals'
		dataType: string
		lineageTag: 0cfd128e-8134-4007-886f-3ed2f44a6279
		summarizeBy: none
		sourceColumn: Number of Meals

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Portion Size'
		dataType: string
		lineageTag: db91c5b0-e0d9-41af-922c-22127b6627a3
		summarizeBy: none
		sourceColumn: Portion Size

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Preselected Mealbox Product Id'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1600489b-556a-403f-b1d5-e4b9e7412e1a
		summarizeBy: none
		sourceColumn: Preselected Mealbox Product Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    dim_products_Table = gold_Schema{[Name="dim_products",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dim_products_Table,{{"product_variation_id", "Product Variation Id"}, {"product_id", "Product Id"}, {"product_concept_name", "Product Concept Name"}, {"product_type_name", "Product Type Name"}, {"product_name", "Product Name"}, {"product_status_name", "Product Status Name"}, {"product_variation_name", "Product Variation Name"}, {"sku", "Sku"}, {"number_of_meals", "Number of Meals"}, {"number_of_portions", "Portion Size"}, {"preselected_mealbox_product_id", "Preselected Mealbox Product Id"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

