/// Includes information about all main recipes that exist in the recipe universe or
/// has been used in a menu week after 2019, and all the variations of the main recipe.
/// Can be used to filter measures on different recipe dimensions such as cooking time, main ingredient etc.
table Recipes
	lineageTag: bd92b28f-2317-4cec-b83c-99b43a1927d2

	/// Number of Main Recipe Ids that exist in the recipe universe or menu variations (after 2019)
	/// This measure can only be used together with other field in the same table.
	/// I.e., can not be filtered using other tables such as Date or Products. 
	measure 'Number of Main Recipe Ids in Table' = DISTINCTCOUNTNOBLANK('Recipes'[Main Recipe Id])
		formatString: #,0
		displayFolder: Recipes Table Measures
	
	column pk_dim_recipes
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 9be2f58b-3057-4263-938e-6d2de6a5f3ca
		summarizeBy: none
		sourceColumn: pk_dim_recipes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The unique identifier of a weekly variation of a main recipe.
	column 'Recipe Id'
		dataType: string
		formatString: 0
		lineageTag: 48e9feba-edf6-45fa-8bde-6e41295105b4
		summarizeBy: distinctCount
		sourceColumn: recipe_id
		sortByColumn: 'Recipe Id - Sort'

		annotation SummarizationSetBy = Automatic

	/// The unique identifier of a weekly variation of a main recipe.
	column 'Recipe Id - Sort'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: Recipe Id - Sort

		annotation SummarizationSetBy = Automatic

	column recipe_status_code_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e1147db8-bdb8-4156-96c7-044f4d37fd63
		summarizeBy: none
		sourceColumn: recipe_status_code_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The lower end of the specified cooking time range.
	column 'Cooking Time From'
		dataType: int64
		formatString: 0
		lineageTag: 09163257-1ebb-4768-9c79-989c2d75f3fc
		summarizeBy: none
		sourceColumn: cooking_time_from

		annotation SummarizationSetBy = Automatic

	/// The higher end of the specified cooking time range.
	column 'Cooking Time To'
		dataType: int64
		formatString: 0
		lineageTag: 57887c9e-bd3a-4ec3-b197-9119f93156bf
		summarizeBy: none
		sourceColumn: cooking_time_to

		annotation SummarizationSetBy = Automatic

	/// The full recipe name in local language.
	column 'Recipe Name'
		dataType: string
		lineageTag: fe9bf7f7-27df-4365-b1ad-e0218690634d
		summarizeBy: none
		sourceColumn: recipe_name

		annotation SummarizationSetBy = Automatic

	/// The specified difficulty level of the recipe. I.e. how quick the recipe is to cook.
	column 'Recipe Difficulty'
		dataType: string
		lineageTag: 0001f150-74ec-4b7c-a932-df05b4c62272
		summarizeBy: none
		sourceColumn: recipe_difficulty_name

		annotation SummarizationSetBy = Automatic

	/// The name of the specified main ingredient of the recipe, in local language.
	column 'Recipe Main Ingredient Name'
		dataType: string
		lineageTag: 74688ed6-412e-4ef6-9858-c508efec0bc7
		summarizeBy: none
		sourceColumn: recipe_main_ingredient_name_local

		annotation SummarizationSetBy = Automatic

	/// The main recipe name in local language.
	/// All recipes are weekly variations of a main recipe, which is the original recipe.
	/// The main recipe has its name and the recipe name can differ from this original name. 
	column 'Main Recipe Name'
		dataType: string
		lineageTag: 7f2798ef-8885-4969-8934-2c2be899d39b
		summarizeBy: none
		sourceColumn: main_recipe_name

		annotation SummarizationSetBy = Automatic

	/// Indicates if the actual recipe is a main recipe.
	column 'Is Main Recipe'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 77300f20-5de9-4d3b-8988-a7fe5ccc64c3
		summarizeBy: none
		sourceColumn: is_main_recipe

		annotation SummarizationSetBy = Automatic

	/// The name of the specified main ingredient of the recipe, in English.
	column 'Recipe Main Ingredient Name (Eng)'
		dataType: string
		lineageTag: d066e4c4-028f-444b-92cd-3f2edaaa867c
		summarizeBy: none
		sourceColumn: recipe_main_ingredient_name_english

		annotation SummarizationSetBy = Automatic

	column recipe_metadata_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 04359755-28af-42dd-9175-be7ee2eea81a
		summarizeBy: none
		sourceColumn: recipe_metadata_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The id of the main recipe.
	/// All recipes are weekly variations of a main recipe, which is the original recipe.
	/// This id is a reference to this original recipe.
	column 'Main Recipe Id'
		dataType: string
		formatString: 0
		lineageTag: c3fc7509-3987-48cd-87e7-ddb502a6bc02
		summarizeBy: distinctCount
		sourceColumn: main_recipe_id
		sortByColumn: 'Main Recipe Id - Sort'

		annotation SummarizationSetBy = Automatic

	/// Column use for sorting the menu recipe id
	column 'Main Recipe Id - Sort'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: Main Recipe Id - Sort

		annotation SummarizationSetBy = Automatic

	/// Number of times the main recipe has been present in a menu week 
	column 'Menu Week Count (Main Recipe)'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: menu_week_count_main_recipe

		annotation SummarizationSetBy = Automatic

	/// The previous menu week the main recipe was present on the format YYYYWW.
	/// I.e., year 2025 and week 3 is represented as 202503
	column 'Previous Menu Week (Main Recipe)'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: previous_menu_week_main_recipe

	/// Number of weeks since the first menu week where the main recipe id was present
	/// Is 0 if the current calendar week is the first menu week with the main recipe id
	/// Is a negative number if the menu week is in the future
	column 'Weeks Since First Menu Week (Main Recipe)'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: weeks_since_first_menu_week_main_recipe

		annotation SummarizationSetBy = Automatic

	/// A unique id of the actual recipe which is a merger of the Main Recipe Id and the Main Recipe Variaion Suffix with a hyphen in between.
	/// The main recipe will have no Main Recipe Variation Id (I.e. it wil be NULL).
	column 'Main Recipe Variation Id'
		dataType: string
		lineageTag: c5361d62-b3ca-4475-8af7-6bbe1e6a1ae4
		summarizeBy: none
		sourceColumn: main_recipe_variation_id

		annotation SummarizationSetBy = Automatic

	/// The ordinal number of the weekly variation of the main recipe.
	/// All recipes are weekly variations of a main recipe, which is the original recipe.
	/// Every time a new variation is created it will get the next ordinal number. The first variation created from the main recipe has ordinal number 00.
	column 'Main Recipe Variation Suffix'
		dataType: string
		lineageTag: 5f85679f-9b62-4f58-8e95-89f670bcacdb
		summarizeBy: none
		sourceColumn: main_recipe_variation_suffix

		annotation SummarizationSetBy = Automatic

	column recipe_main_ingredient_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: d18ed834-b187-4ce0-8db5-e202ba1c1fcb
		summarizeBy: none
		sourceColumn: recipe_main_ingredient_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column recipe_difficulty_level_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e43e0fce-7388-4677-a44c-ca858eae159b
		summarizeBy: none
		sourceColumn: recipe_difficulty_level_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column language_id
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 13d97f09-570e-4614-9809-b300a2cfdf25
		summarizeBy: none
		sourceColumn: language_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The specified cooking time range of the recipe.
	column 'Cooking Time'
		dataType: string
		lineageTag: 56d08ed4-ea04-4d27-b993-640873c82ae4
		summarizeBy: none
		sourceColumn: cooking_time
		sortByColumn: cooking_time_sorting

		annotation SummarizationSetBy = Automatic

	column cooking_time_sorting
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: cooking_time_sorting

	/// True if a recipe photo has been uploaded in the internal system.
	column 'Has Recipe Photo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 34503937-ad7d-4cf0-af16-2eca1da8c3f7
		summarizeBy: none
		sourceColumn: has_recipe_photo

		annotation SummarizationSetBy = Automatic

	/// The specified caption of the recipe photo.
	column 'Recipe Photo Caption'
		dataType: string
		lineageTag: 8b4312df-ca77-44b4-a594-3d7f880e124d
		summarizeBy: none
		sourceColumn: recipe_photo_caption

		annotation SummarizationSetBy = Automatic

	/// A comment on the recipe to be published externally.
	column 'Recipe General Text'
		dataType: string
		lineageTag: 29ca386e-232e-40a5-98b8-12d0dd41828e
		summarizeBy: none
		sourceColumn: recipe_general_text

		annotation SummarizationSetBy = Automatic

	/// The description of the recipe to be published externally.
	column 'Recipe Description'
		dataType: string
		lineageTag: 77cf6690-bdd2-4014-bb02-4346f9b95c58
		summarizeBy: none
		sourceColumn: recipe_description

		annotation SummarizationSetBy = Automatic

	/// True if the recipe has been selected for the "Recipe Universe".
	/// The Recipe Universe contains the recipes that Physical Product Team has decided can be used.
	column 'Is In Recipe Universe'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 59b8101c-0ee7-482f-89d0-2adcbc82a050
		summarizeBy: none
		sourceColumn: is_in_recipe_universe

		annotation SummarizationSetBy = Automatic

	/// The maximum number of days that the customer can wait before cooking the recipe.
	column 'Recipe Shelf Life Days'
		dataType: int64
		formatString: 0
		lineageTag: 70301a02-ea3e-4f35-b8f4-b9d0298fd476
		summarizeBy: none
		sourceColumn: recipe_shelf_life_days

		annotation SummarizationSetBy = Automatic

	/// The recipe internal comment.
	column 'Recipe Comment'
		dataType: string
		lineageTag: 73348bb0-601b-4f7c-91c7-0f318fa23631
		summarizeBy: none
		sourceColumn: recipe_comment

		annotation SummarizationSetBy = Automatic

	/// The recipe chef's tip to be published externally.
	column 'Recipe Chef Tip'
		dataType: string
		lineageTag: efe9cfc6-0711-4994-ae0e-7db32de8d2b9
		summarizeBy: none
		sourceColumn: recipe_chef_tip

		annotation SummarizationSetBy = Automatic

	partition Recipes = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(Host, HttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    catalog_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    gold_Schema = catalog_Database{[Name=Schema,Kind="Schema"]}[Data],
				    dim_recipes_Table = gold_Schema{[Name="dim_recipes",Kind="Table"]}[Data],
					#"Added Recipe Sort Col" = Table.DuplicateColumn(dim_recipes_Table, "recipe_id", "Recipe Id - Sort"),
				    #"Added Main Recipe Sort Col" = Table.DuplicateColumn(#"Added Recipe Sort Col", "main_recipe_id", "Main Recipe Id - Sort")
				in
					#"Added Main Recipe Sort Col"

	annotation PBI_ResultType = Table
