[tool.poetry]
name = "embeddings"
version = "0.1.0"
description = "A package to simplify the usage of embeddings"
authors = ["Mats Eikeland Mollestad <mats.mollestad@cheffelo.com>"]
packages = [{include = "embeddings"}]

[tool.poetry.dependencies]
python = "^3.10"
polars = { version = "*", optional = true }
pandas = { version = "*", optional = true }
openai = { version = "^1.63.2", optional = true }
tiktoken = { version = "^0.9.0", optional = true }
sentence-transformers = { version = "*", optional = true }

[tool.poetry.extras]
polars = ["polars"]
pandas = ["pandas"]
openai = ["openai", "tiktoken"]
sentence-transformers = ["sentence-transformers"]

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-mock = "*"
pyright = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
