version: '3'
services:
  rec-engine:
    platform: linux/amd64
    image: rec-engine-rec-engine
    build:
      context: ../../
      dockerfile: projects/rec-engine/Dockerfile
    command: ["echo", "'Hello from Rec Engine'"]
    volumes:
      - ./rec_engine:/opt/projects/rec-engine/rec_engine
      - ./../../packages:/opt/packages


  rec-engine-app:
    platform: linux/amd64
    image: rec-engine-rec-engine
    build:
      context: ../../
      dockerfile: projects/rec-engine/Dockerfile
    volumes:
      - ./:/opt/projects/rec-engine/
      - ./../../packages:/opt/packages
    command: ["python", "-m", "streamlit", "run", "app_ui.py", "--server.fileWatcherType", "poll"]
    depends_on:
      - rec-engine
    ports:
      - 8501:8501
    env_file:
      - ../../.env
      - .env

  local-run:
    platform: linux/amd64
    image: rec-engine-databricks
    build:
      context: ../../
      dockerfile: projects/rec-engine/Dockerfile.databricks
    command: "python -m rec_engine.main"
    volumes:
      - ./:/opt/projects/rec-engine/
      - ./../../packages:/opt/packages
    env_file:
      - ../../.env
      - .env

  jupyter:
    platform: linux/amd64
    image: rec-engine-jupyter
    build:
      context: ../../
      dockerfile: projects/rec-engine/Dockerfile.jupyter
    command: "jupyter notebook --allow-root --ip=0.0.0.0 --port=8888"
    ports:
      - 8888:8888
    volumes:
      - ./:/opt/projects/rec-engine/
      - ./../../packages:/opt/packages
    env_file:
      - ../../.env
      - .env


  rec-engine-test:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/rec-engine/Dockerfile.test
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/rec-engine
      - ./../../packages:/opt/packages
    depends_on:
      - rec-engine
