services:

  data-catalog:
    image: data-catalog-data-catalog-app
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
    command: ["echo", "'Hello from data-catalog'"]
    volumes:
      - ./:/opt/projects/data-catalog
      - ./../../packages:/opt/packages
    working_dir: "/app"

  data-catalog-app:
    platform: linux/amd64
    image: data-catalog-data-catalog-app
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
    command: ["python", "-m", "streamlit", "run", "/app/app.py", "--server.fileWatcherType", "poll"]
    profiles: ["catalog"]
    ports:
      - 8000:8501
    volumes:
      - ./data_catalog/load_contracts.py:/app/custom_store.py
      - ./../../packages:/app/packages
    env_file:
      - ../../.env
    working_dir: "/app"
    deploy:
      resources:
        limits:
          # Max 14 GB of memory
          memory: 20GB

  data-catalog-test:
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile.testing
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/data-catalog
      - ./../../packages:/opt/packages
    depends_on:
      - data-catalog
