services:
  data-catalog:
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
    ports:
    - 8502:8501
    volumes:
    - ./data_catalog:/opt/projects/data-catalog/data_catalog
  data-catalog-streamlit:
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
    command: python -m streamlit run /opt/projects/data-catalog/app/app.py
    ports:
    - 8501:8501
version: '3'
