services:

  catalog:
    image: matsmoll/aligned-catalog
    command: "fastapi run aligned_cloud/api.py --host 0.0.0.0 --port 8000"
    volumes:
      - ${PWD}/contract_store.json:/app/aligned-cloud/contract_store.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow.raspberrypi.local
      - HOST_URL=http://127.0.0.1:8000
      - LOCAL_VOLUME=${PWD}
    ports:
      - 8000:8000
    env_file:
      - ../../.env

  valkey:
    image: valkey/valkey:8.1
    environment:
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - '${PWD}/../../.data/valkey:/data'


  data-catalog-test:
    image: data-contracts-test
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
      args:
        POETRY_ARGS: --with=dev
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/data-catalog
      - ./../../packages:/opt/packages
    environment:
      - REDIS_URL=redis://valkey:6379
    depends_on:
      - valkey

  databricks:
    image: data-contracts-databricks
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./projects/data-catalog/Dockerfile
    command: ["python", "-m", "jobs.materialize"]
    volumes:
      - ./:/opt/projects/data-catalog
      - ./../../packages:/opt/packages
