version: '3'
services:
  {{cookiecutter.project_name}}:
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/Dockerfile
    volumes:
      - ./{{cookiecutter.module_name}}:/opt/projects/{{cookiecutter.project_name}}/{{cookiecutter.module_name}}

  {{cookiecutter.project_name}}-app:
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/Dockerfile
    volumes:
      - ./{{cookiecutter.module_name}}:/opt/projects/{{cookiecutter.project_name}}/{{cookiecutter.module_name}}
      - ./app:/opt/projects/{{cookiecutter.project_name}}/app
    command: ["python", "-m", "streamlit", "run", "app/main.py"]
    ports:
      - 8501:8501
