version: '3'
services:
  # {{cookiecutter.project_name}}:
  #   build:
  #     context: ../../
  #     dockerfile: projects/{{ cookiecutter.project_name }}/Dockerfile
  #   volumes:
  #     - ./{{cookiecutter.module_name}}:/opt/projects/{{cookiecutter.project_name}}/{{cookiecutter.module_name}}

  {{cookiecutter.project_name}}-app:
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/Dockerfile
    volumes:
      - ./:/opt/projects/{{cookiecutter.project_name}}
      - ./../../packages:/opt/packages
    command: ["python", "-m", "streamlit", "run", "app.py"]
    ports:
      - 8501:8501
