version: '3'
services:

  # This service mainly serves as a build step. Therefore, making sure the Dockerfile is build
  # It will also be used when starting a shell
  base:
    image: {{cookiecutter.project_name}}-base
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/docker/Dockerfile
    command: ["echo", "'Hello from {{cookiecutter.project_name}}'"]
    volumes:
      - ./:/opt/projects/{{cookiecutter.project_name}}
      - ./../../packages:/opt/packages

  test:
    image: {{cookiecutter.project_name}}-test
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/docker/Dockerfile.testing
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/{{cookiecutter.project_name}}
      - ./../../packages:/opt/packages
    depends_on:
      - base
    profiles: ["test"]
