version: '3'
services:
  {{cookiecutter.project_name}}:
    build:
      context: ../../
      dockerfile: projects/{{ cookiecutter.project_name }}/Dockerfile
    volumes:
      - ./{{cookiecutter.module_name}}:/opt/{{cookiecutter.project_name}}/{{cookiecutter.module_name}}
    ports:
      - 8501:8501
