FROM databricksruntime/python:15.4-LTS

SHELL ["/bin/bash", "-c"]

# Defaulting to utf-8 to fixe a few charset bugs
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# set the home directory
ENV APP_HOME /opt
ENV SERVICE_HOME $APP_HOME/projects/ab-test-analysis

RUN /databricks/python3/bin/pip install poetry

# copy source code
WORKDIR $APP_HOME
COPY packages packages

WORKDIR $SERVICE_HOME
COPY projects/ab-test-analysis/pyproject.toml .
COPY projects/ab-test-analysis/poetry.lock .

# create a dummy package to satisfy Poetry
RUN mkdir -p ab_test_analysis && touch ab_test_analysis/__init__.py

RUN source /databricks/python3/bin/activate \
	&& echo "$(which poetry)" \
	&& poetry config virtualenvs.create false \
	&& poetry install --without=dev


ENV PYTHONPATH /databricks/python3/bin
ENV PATH /databricks/python3/bin:$PATH

# copy source code
COPY projects/ab-test-analysis .

WORKDIR $SERVICE_HOME
CMD python ab_test_analysis/main.py
