name: 'transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'transform'

# These configurations specify where dbt should look for different types of files.
# For Databricks asset bundles, we put everything in src, as you may have
# non-dbt resources in your project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
 future_proof_date: '9999-12-31'
 onesub_beta_launch_date: '2024-10-14'
 mealbox_adjustments_cutoff: '2024-01-01'
 preselector_origin_id: '6AD5DF6F-6CDA-4E45-96D0-A169B633247C'
 mealselector_origin_id: '9E016A92-9E5C-4B5B-AC5D-739CEFD6F07B'
 normal_origin_id: '25017D0E-F788-48D7-8DC4-62581D58B698'
 onesub_product_id: 'D699150E-D2DE-4BC1-A75C-8B70C9B28AE3'
 mealbox_product_type_id: '2F163D69-8AC1-6E0C-8793-FF0000804EB3'
 financial_product_type_id: '288ED8CA-B437-4A6D-BE16-8F9A30185008'
 velg&vrak_product_type_id: 'CAC333EA-EC15-4EEA-9D8D-2B9EF60EC0C1'
 incremental_number_of_days: 30
 full_load_first_date: '2024-01-15'
 subscription_order_type_ids: [
          "'1C182E51-ECFA-4119-8928-F2D9F57C5FCC'", #Orders after cutoff
          "'5F34860B-7E61-46A0-80F7-98DCDC53BA9E'", #Recurring
          "'C7D2684C-B715-4C6C-BF90-053757926679'"  #Order After Registration
]
 finished_order_status_ids: [
          "'38A5CC25-A639-4433-A8E6-43FB35DABFD9'", #Processing
          "'4508130E-6BA1-4C14-94A4-A56B074BB135'"  #Finished
]
 basket_history_start_at: '2023-11-01 00:00:00'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# These settings can be overridden in the
# individual model files using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  transform:
    +materialized: table

    silver:
      +schema: silver
      postgres:
        base:
          +materialized: table

    intermediate:
      +schema: intermediate
      +materialized: "{{ 'table' if target.database == 'dev' else 'ephemeral' }}"

    gold:
      +schema: gold

    mlgold:
      +schema: mlgold

    drafts:
      +schema: draft
      +materialized: ephemeral
      +enabled: false