name: 'transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'transform'

# These configurations specify where dbt should look for different types of files.
# For Databricks asset bundles, we put everything in src, as you may have
# non-dbt resources in your project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
 english_language_id: 4
 norwegian_language_id: 1
 swedish_language_id: 5
 danish_language_id: 6
 future_proof_date: '9999-12-31'
 onesub_beta_launch_date: '2024-10-14'
 onesub_full_launch_date: '2024-11-18'
 mealbox_adjustments_cutoff: '2024-01-01'
 preselector_origin_id: '6AD5DF6F-6CDA-4E45-96D0-A169B633247C'
 mealselector_origin_id: '9E016A92-9E5C-4B5B-AC5D-739CEFD6F07B'
 normal_origin_id: '25017D0E-F788-48D7-8DC4-62581D58B698'
 onesub_product_id: 'D699150E-D2DE-4BC1-A75C-8B70C9B28AE3'
 mealbox_product_type_id: '2F163D69-8AC1-6E0C-8793-FF0000804EB3'
 financial_product_type_id: '288ED8CA-B437-4A6D-BE16-8F9A30185008'
 velg&vrak_product_type_id: 'CAC333EA-EC15-4EEA-9D8D-2B9EF60EC0C1'
 grocery_product_type_ids: [
          "'E146C37C-DD49-42C7-8A78-6BB647021F66'", #Add-on-product
          "'ADB241C3-DECA-4FD7-A173-923BE1A7ABD3'" #Standalone-groceries
]
 mealbox_basket_type_id: '550C0EF6-CD4E-487E-9F19-0CC929152497'
 grocery_basket_type_id: '1F72B8C1-D765-426D-88E3-EC412FB7F4B7'
 basket_split_migration_date: '2025-05-08'
 incremental_number_of_days: 30
 full_load_first_date: '2023-01-01'
 subscription_order_type_ids: [
          "'1C182E51-ECFA-4119-8928-F2D9F57C5FCC'", #Orders after cutoff
          "'5F34860B-7E61-46A0-80F7-98DCDC53BA9E'", #Recurring
          "'C7D2684C-B715-4C6C-BF90-053757926679'"  #Order After Registration
]
 daily_direct_order_type_id: 'C4C44413-78A7-4EB8-8715-2643D88849B6'
 campaign_order_type_id: '7DB44860-1075-49A1-BF37-9B4D5B9C4BA4'
 finished_order_status_ids: [
          "'38A5CC25-A639-4433-A8E6-43FB35DABFD9'", #Processing
          "'4508130E-6BA1-4C14-94A4-A56B074BB135'"  #Finished
]
 basket_history_start_at: '2023-11-01 00:00:00'

 active_company_ids: [
  "'6A2D0B60-84D6-4830-9945-58D518D27AC2'", #Linas Matkasse
  "'09ECD4F0-AE58-4539-8E8F-9275B1859A19'", #Godtlevert
  "'8A613C15-35E4-471F-91CC-972F933331D7'", #Adams matkasse
  "'5E65A955-7B1A-446C-B24F-CFE576BF52D7'" #Retnemt
 ]

 onesub_chefs_favorite_taxonomy_ids: [
  2011, # Chefs choice, Norwegian
  2147, # Chefs choice, Swedish
  2152 #Chefs choice, Danish
 ]
 onesub_vegetarian_taxonomy_ids: [
  2012, # Vegetarian, Norwegian
  2150, # Vegetarian, Swedish
  2155, # Vegetarian, Danish
  2157 # Vegan, Swedish
 ]
 onesube_low_calorie_taxonomy_ids: [
  2015, # Roede, Norwegian
  2096, # Roede, Norwegian
  2156, # Low calorie, Danish
  2013, # Low calorie, Norwegian
  2151 # Low calorie, Swedish
 ]
 onesub_quick_and_easy_taxonomy_ids: [
  2010, # Express, Norwegian
  2149, # Express, Swedish
  2154 # Express, Danish
 ]
 onesub_family_friendly_taxonomy_ids: [
  2148, # Family, Swedish
  2014, # Family, Norwegian
  2153, # Family, Danish
  1213, # Barnevennlig, Norwegian
  1321, # Børnevenlig, Danish
  2095, # Barnvänligt, Swedish
  2199, # Familievenlig, Danish
  1148, # Familjefavoriter, Swedish
  226 # Barnevennlig, Norwegian
 ]

 nutrient_id_fat: 2
 nutrient_id_protein: 3
 nutrient_id_carbs: 5
 nutrient_id_salt: 6
 nutrient_id_kJ: 7
 nutrient_id_saturated_fat: 8
 nutrient_id_sugar: 9
 nutrient_id_fiber: 10
 nutrient_id_kcal: 11
 nutrient_id_fresh_fruit_veg: 12
 nutrient_id_processed_fruit_veg: 13
 nutrient_id_added_sugars: 14
 nutrient_id_added_salt: 15
 countries:
    norway:
      country_id: '55BBF40F-3693-478E-948A-FB2321DB7771'
      pickup_location_postal_code_id: 9876
      postal_code_length: 4
    sweden:
      country_id: '4298F454-C79C-45E7-8FAF-3DDFE9440F46'
      pickup_location_postal_code_id: 99999
      postal_code_length: 5
    denmark:
      country_id: 'D08EA478-447C-4A66-B9EC-D6ABD3697C02'
      pickup_location_postal_code_id: 1
      postal_code_length: 4

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# These settings can be overridden in the
# individual model files using the `{{ config(...) }}` macro.

snapshots:
  +target_schema: "dbt_snapshots"

models:
  +persist_docs:
    relation: true
    columns: true
  transform:
    +materialized: table

    silver:
      +schema: silver
      postgres:
        base:
          +materialized: table

    intermediate:
      +schema: intermediate
      +materialized: table

    gold:
      +schema: gold

    mlgold:
      +schema: mlgold

    drafts:
      +schema: draft
      +materialized: ephemeral
      +enabled: false

seeds:
  +schema: seeds
  +delimiter: ';'
