version: '3'
services:

  # This service mainly serves as a build step. Therefore, making sure the Dockerfile is build
  # It will also be used when starting a shell
  base:
    image: ml-example-project-base
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/ml-example-project/docker/Dockerfile
    command: ["echo", "'Hello from ml-example-project'"]
    volumes:
      - ./:/opt/projects/ml-example-project
      - ./../../packages:/opt/packages

  test:
    image: ml-example-project-test
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/ml-example-project/docker/Dockerfile.testing
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/ml-example-project
      - ./../../packages:/opt/packages
    depends_on:
      - base
    profiles: ["test"]
