version: '3'
services:

  # This service mainly serves as a build step. Therefore, making sure the Dockerfile is build
  # It will also be used when starting a shell
  orders-forecasting:
    image: orders-forecasting-orders-forecasting
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/orders-forecasting/Dockerfile
    command: ["bash"]
    volumes:
      - ./:/opt/projects/orders-forecasting
      - ./../../packages:/opt/packages

  orders-forecasting-app:
    image: order-forecasting-app
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/order-forecasting/Dockerfile
    volumes:
      - ./:/opt/projects/order-forecasting
      - ./../../packages:/opt/packages
    command: ["python", "-m", "streamlit", "run", "app.py"]
    ports:
      - 8501:8501
    depends_on:
      - orders-forecasting
    env_file:
      - .env

  orders-forecasting-test:
    image: order-forecasting-test
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/order-forecasting/Dockerfile.testing
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/order-forecasting
      - ./../../packages:/opt/packages
    depends_on:
      - orders-forecasting
    profiles: ["test"]
