[tool.poetry]
name = "lmkgroup_ds_utils"
version = "0.0.28"
description = "Utilities for the data science team at LMK Group"
authors = ["Thomas Astad Sve <thomas.sve@godtlevert.no>"]
packages = [{include = "lmkgroup_ds_utils"}]

[tool.poetry.dependencies]
python = "^3.8"

azure-storage-blob = {version = "12.13.0", optional = true }
azure-identity = {version = "1.10.0", optional = true }
pandas = {version = "2.0.1", optional = true }
redis = {version = "^4.3.4", optional = true }
pyodbc = {version = "4.0.34", optional = true }
psycopg2 = {version = "^2.9.5", optional = true }
SQLAlchemy = {version = "^1.4.42", optional = true }

[tool.poetry.extras]
datalake = ["azure-storage-blob", "azure-identity"]
msdb = ["pyodbc", "SQLAlchemy"]
pandas = ["pandas"]
postgres = ["psycopg2", "SQLAlchemy"]
redis = ["redis"]

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
