
filter:
  portion_size: True
  taste_restrictions: True
ranking:
  quarantine: True
  num_quarantine_weeks: 4
  rec_engine: True
rules:
  preference_rules: True
  protein_variety: True
  cost_of_food: False
basket_combinations:
  max: 100
