services:

  # This service mainly serves as a build step. Therefore, making sure the Dockerfile is build
  # It will also be used when starting a shell
  agent:
    image: gcr.io/datadoghq/agent:latest
    platform: linux/amd64
    env_file:
      - ../../.env
      - .env
    ports:
      - 8125:8125/udp

  preselector:
    image: preselector-preselector
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
      args:
        - DEP_GROUP=--without=dev
    command: ["echo", "'Hello from preselector'"]
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    env_file:
      - ../../.env
      - .env

  combination-app:
    platform: linux/amd64
    image: preselector-combo
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
      args:
        - DEP_GROUP=--with=worker
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    command: "python -m streamlit run streamlit_apps/combinations_app.py --server.folderWatchList /opt/projects/preselector/preselector"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 8506:8501
    depends_on:
      - preselector
    env_file:
      - .env
      - ../../.env

  preselector-test:
    platform: linux/amd64
    image: preselector-test
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
    command: ["python", "-m", "pytest", "-rav", "tests"]
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    depends_on:
      - preselector


  preview-server:
    platform: linux/amd64
    image: preselector-test
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
    command: "fastapi dev preselector/preview_server.py --host 0.0.0.0"
    ports:
      - 8001:8000
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    depends_on:
      - preselector
    env_file:
      - .env
      - ../../.env

  debug:
    platform: linux/amd64
    image: preselector-preselector
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    command: "python -m streamlit run streamlit_apps/debug_app.py --server.folderWatchList /opt/projects/preselector/preselector"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 8507:8501
    depends_on:
      - preselector
    env_file:
      - .env
      - ../../.env

  databricks:
    platform: linux/amd64
    image: preselector-databricks
    build:
      context: ../../
      dockerfile: projects/preselector/docker/Dockerfile.databricks
    command: "echo 'hello'"
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    env_file:
      - ../../.env
      - .env

  process-stream:
    platform: linux/amd64
    image: preselector-worker
    build:
      context: ../../
      dockerfile: projects/preselector/Dockerfile
      args:
        - DEP_GROUP=--with=worker
    volumes:
      - ./:/opt/projects/preselector
      - ./../../packages:/opt/packages
    command: "/usr/local/bin/python -m preselector.process_stream"
    depends_on:
      - preselector
    env_file:
      - .env
      - ../../.env
    deploy:
      resources:
        limits:
          # Max 14 GB of memory
          memory: 7GB
