[tool.poetry]
name = "data_connector"
version = "0.1.0"
description = "Connector to retrieve data from different data sources"
authors = ["Thomas Sve <thomas.sve@cheffelo.com>"]
packages = [{include = "data_connector"}]

[tool.poetry.dependencies]
python = "^3.10"
databricks-sdk = "^0.25.1"
databricks-sql-connector = "^3.1.1"
numpy = "1.26.4"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
ruff = "*"
chef = {path = "../../packages/chef", develop = true}
pyspark = "^3.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
