---
    name: AB Test Analysis PR Pipeline

    on:
      pull_request:
        paths:
          - '.github/workflows/test_in_docker.yml'
          - '.github/workflows/ab_test_analysis_pr.yml'
          - 'projects/ab-test-analysis/**'
      workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

    jobs:
      ci-libs-ab-test-analysis:
        uses:
          ./.github/workflows/python_reusable.yml
        with:
          working-directory: projects/ab-test-analysis
        secrets: inherit

      build-ab-test-analysis-databricks-image:
        uses: ./.github/workflows/cd_docker_image_template.yml
        with:
          working-directory: projects/ab-test-analysis
          registry: ${{ vars.CONTAINER_REGISTRY }}
          image-name: ab-test-analysis-databricks
          dockerfile: docker/Dockerfile.databricks
          tag: dev-latest
        secrets: inherit
