name: analytics-api PR
on:
  pull_request:
    paths:
      - '.github/workflows/analytics-api_pr.yaml'
      - 'projects/analytics-api/**'
      - 'projects/menu-optimiser/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  test-analytics-api:
    uses: ./.github/workflows/template_test_python.yml
    with:
      python-version: "3.10.13"
      working-directory: projects/analytics-api
    secrets: inherit

  build-analytics-api-image:
    uses: ./.github/workflows/cd_docker_image_template.yml
    with:
      working-directory: projects/analytics-api
      registry: ${{ vars.CONTAINER_REGISTRY }}
      image-name: analytics-api
      dockerfile: docker/Dockerfile
      tag: dev-latest
    secrets: inherit
