name: 'Deploy Databricks DABs...'

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "The project directory to deploy. Should contain a databricks.yml file in the root"
      target-env:
        required: true
        type: string
      extra-args:
        type: string
        default: ""
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  databricks-deploy:
    name: 'Deploy DABs in ${{inputs.working-directory}}'
    runs-on: ubuntu-22.04
    environment: ${{inputs.target-env}}
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}
    env:
      DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"
      DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Databricks CLI
      uses: databricks/setup-cli@v0.212.2

    - name: Validate DABs
      run: databricks bundle validate --target ${{ vars.ENVIRONMENT_VARIABLE }} ${{inputs.extra-args}}

    - name: Deploy DABs
      run: databricks bundle deploy --target ${{ vars.ENVIRONMENT_VARIABLE }} ${{inputs.extra-args}}
