name: Data Model Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/cd_data_model.yml'
      - 'projects/data-model**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  dbt-manifest-upload:
    strategy:
      matrix:
        target: [Test, Production]
      fail-fast: true
    uses: ./.github/workflows/dbt_manifest_upload.yml
    with:
      working-directory: projects/data-model
      python-version: "3.11"
      target-env: ${{matrix.target}}
    secrets: inherit

  deploy-dab:
    strategy:
      matrix:
        target: [Test, Production]
      max-parallel: 1
      fail-fast: true
    needs: dbt-manifest-upload
    uses: ./.github/workflows/cd_dab_template.yml
    with:
      working-directory: projects/data-model
      target-env: ${{matrix.target}}
      should-change-target: true
    secrets: inherit
