name: 'Deploy Databricks DABs...'

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "The project directory to deploy. Should contain a databricks.yml file in the root"
      target-env:
        required: true
        type: string
        description: "Target environment in Github Actions"
      extra-args:
        type: string
        default: ""
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  databricks-deploy:
    name: 'Deploy DABs in ${{inputs.working-directory}}'
    runs-on: ubuntu-22.04
    environment: ${{inputs.target-env}}
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Azure credentials
      uses: azure/login@v1.4.7
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Databricks CLI
      uses: databricks/setup-cli@v0.215.0

    - name: Validate DABs
      run: databricks bundle validate --target ${{ vars.ENVIRONMENT_VARIABLE }} ${{inputs.extra-args}}

    - name: Deploy DABs
      run: databricks bundle deploy --target ${{ vars.ENVIRONMENT_VARIABLE }} ${{inputs.extra-args}}
