name: 'Deploy Databricks DABs...'

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "The project directory to deploy. Should contain a databricks.yml file in the root"
      target-env:
        required: true
        type: string
        description: "Target environment in Github Actions"
      extra-args:
        type: string
        default: ""
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  databricks-deploy:
    name: 'Deploy DABs in ${{inputs.working-directory}}'
    runs-on: ubuntu-22.04
    environment: ${{inputs.target-env}}
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Azure credentials
      uses: azure/login@v1.4.7
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Secrets from Key Vault
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az keyvault update --name kv-chefdp-common --resource-group rg-chefdp-common --default-action Allow
          DATABRICKS_SP_BUNDLE_PAT=$(az keyvault secret show --vault-name kv-chefdp-common --name databricks-sp-bundle-pat-${{ vars.ENVIRONMENT_VARIABLE }} --query value -o tsv)
          az keyvault update --name kv-chefdp-common --resource-group rg-chefdp-common --default-action Deny

          echo "::add-mask::${DATABRICKS_SP_BUNDLE_PAT}"
          echo "DATABRICKS_SP_BUNDLE_PAT=${DATABRICKS_SP_BUNDLE_PAT}" >> $GITHUB_ENV

    - name: Setup Databricks CLI
      uses: databricks/setup-cli@v0.224.1

    - name: Validate DABs
      run: databricks bundle validate ${{inputs.extra-args}}
      env:
        DATABRICKS_TOKEN: ${{ env.DATABRICKS_SP_BUNDLE_PAT }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

    - name: Deploy DABs
      run: databricks bundle deploy ${{inputs.extra-args}}
      env:
        DATABRICKS_TOKEN: ${{ env.DATABRICKS_SP_BUNDLE_PAT }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
