---
name: CI projects/data-model

on:
  pull_request:
    paths:
      - '.github/workflows/dbt_reusable.yml'
      - '.github/workflows/ci_data_model.yml'
      - 'projects/data-model**'

  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-data-model-image:
    uses: ./.github/workflows/cd_docker_image_template.yml
    with:
      working-directory: projects/data-model
      registry: ${{ vars.CONTAINER_REGISTRY }}
      image-name: data-model-databricks
      dockerfile: Dockerfile.databricks
      tag: dev-latest
    secrets: inherit

  deploy-dab-to-dev:
    uses: ./.github/workflows/cd_dab_template.yml
    # needs: build-data-model-image # Comment out when setuptools bug is fixed
    with:
      working-directory: projects/data-model
      target-env: Development
      # Setting extra-args to null as it is not needed
      extra-args: '--var="docker_image_url=${{ vars.CONTAINER_REGISTRY }}/data-model-databricks:dev-latest"'
    secrets: inherit

  deploy-dbt-to-dev:
    uses: ./.github/workflows/dbt_reusable.yml
    with:
      working-directory: projects/data-model
      python-version: "3.11"
      target-env: Development
      dbt-target: ci
    secrets: inherit
