---
name: CI projects/data-model

on:
  pull_request:
    paths:
      - '.github/workflows/ci_data_model.yml'
      - 'projects/data_model**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  # Add tests for data platform here.

  deploy-to-dev:
    uses: ./.github/workflows/cd_dab_template.yml
    with:
      working-directory: projects/data-model
      target-env: Development
      # Setting extra-args to null as it is not needed
      extra-args: ''
    secrets: inherit
