---
name: CI projects/my-awesome-project

on:
  pull_request:
    paths:
      - '.github/workflows/python_reusable.yml'
      - '.github/workflows/ci_my_awesome_project.yml'
      - 'projects/my-awesome-project**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-libs-my-awesome-project:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: projects/my-awesome-project
    secrets: inherit
