---
name: CI projects/vector-search

on:
  pull_request:
    paths:
      - '.github/workflows/python_reusable.yml'
      - '.github/workflows/ci_vector_search.yml'
      - 'packages/vector_search/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-libs-vector-search:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: packages/vector_search
    secrets: inherit