name: Clean Containers
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean-containers:
    name: 'Clean all containers in ACR'
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: "packages/container-cleaner"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Azure credentials
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.8.2

      - run: |
          python -m venv .venv --upgrade-deps
          source .venv/bin/activate
          poetry install --no-interaction --all-extras
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Delete Tags
        run: python -m container_cleaner.acr
