---
name: Reusable dbt CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
      python-version:
        required: false
        type: string
      target-env:
        required: true
        type: string
        description: "Target environment in Github Actions"
      # TODO: Not being used
      install-packages:
        description: "Space seperated list of packages to install using apt-get."
        default: ""
        type: string
      # TODO: Did not understand the message under here
      # To avoid being billed 360 minutes if a step does not terminate
      # (we've seen the setup-python step below do so!)
      ci-timeout:
        description: "The timeout of the ci job. Default is 25min"
        default: 25
        type: number
      dbt-target:
        required: true
        type: string
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  dbt-ci:
    name: 'Deploy dbt models in ${{inputs.working-directory}}'
    runs-on: ubuntu-22.04
    environment: ${{ inputs.target-env }}
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: ${{ inputs.python-version }}
          python-version-file: 'pyproject.toml'
          cache: "poetry"
          cache-dependency-path: |
            poetry.lock
            ${{ inputs.working-directory }}/poetry.lock

      - name: Install Python packages
        run: poetry install --with dev

      - name: Install dbt dependencies
        run: poetry run dbt deps --project-dir ./transform

      - name: Configure Azure credentials
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Secrets from Key Vault
        uses: azure/cli@v2
        with:  
          azcliversion: latest
          inlineScript: |
            az keyvault update --name kv-chefdp-common --resource-group rg-chefdp-common --default-action Allow
            
            DATABRICKS_SP_BUNDLE_PAT=$(az keyvault secret show --vault-name kv-chefdp-common --name databricks-sp-bundle-pat-${{ vars.ENVIRONMENT_VARIABLE }} --query value -o tsv)
            DATABRICKS_WAREHOUSE_DBT_ID=$(az keyvault secret show --vault-name kv-chefdp-common --name databricks-warehouse-dbt-id-${{ vars.ENVIRONMENT_VARIABLE }} --query value -o tsv)
            DATABRICKS_WORKSPACE_URL=$(az keyvault secret show --vault-name kv-chefdp-common --name databricks-workspace-url-${{ vars.ENVIRONMENT_VARIABLE }} --query value -o tsv)
            
            az keyvault update --name kv-chefdp-common --resource-group rg-chefdp-common --default-action Deny
            
            echo "::add-mask::${DATABRICKS_SP_BUNDLE_PAT}"
            echo "::add-mask::${DATABRICKS_WAREHOUSE_DBT_ID}"
            echo "::add-mask::${DATABRICKS_WORKSPACE_URL}"
            
            echo "DATABRICKS_SP_BUNDLE_PAT=${DATABRICKS_SP_BUNDLE_PAT}" >> $GITHUB_ENV
            echo "DATABRICKS_WAREHOUSE_DBT_ID=${DATABRICKS_WAREHOUSE_DBT_ID}" >> $GITHUB_ENV
            echo "DATABRICKS_WORKSPACE_URL=${DATABRICKS_WORKSPACE_URL}" >> $GITHUB_ENV

      - name: dbt build
        run: poetry run dbt build --exclude drafts.* --target=${{ inputs.dbt-target }} --full-refresh --project-dir ./transform --profiles-dir ./transform/profiles
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_WORKSPACE_URL }}
          DATABRICKS_HTTP_PATH: /sql/1.0/warehouses/${{ env.DATABRICKS_WAREHOUSE_DBT_ID }}
          DATABRICKS_DBT_TOKEN: ${{ env.DATABRICKS_SP_BUNDLE_PAT }}
