---
name: Deploy Preselector

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/python_reusable.yml'
      - '.github/workflows/deploy_preselector.yml'
      - 'projects/preselector**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-libs-preselector:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: projects/preselector
    secrets: inherit

  deploy-preselector:
    needs:
      - 'ci-libs-preselector'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Azure authentication'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'ACR authentication'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Docker Build & Push to ACR'
      run: |
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/preselector:${{ github.sha }}
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/preselector:latest
        docker push ${{ secrets.CONTAINER_REGISTRY }}/preselector:${{ github.sha }}
        docker push ${{ secrets.CONTAINER_REGISTRY }}/preselector:latest

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: preselector
        images: ${{ secrets.CONTAINER_REGISTRY }}/preselector:${{ github.sha }}
