name: embeddings - Package PR
on:
  pull_request:
    paths:
      - '.github/workflows/embeddings_pr.yaml'
      - 'packages/embeddings/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  test-embeddings:
    uses:
      ./.github/workflows/template_test_python.yml
    with:
      python-version: "3.10"
      working-directory: packages/embeddings
    secrets: inherit
