---
    name: ML Example Project PR Pipeline

    on:
      pull_request:
        paths:
          - '.github/workflows/test_in_docker.yml'
          - '.github/workflows/ml_example_project_pr.yml'
          - 'projects/ml-example-project/**'
      workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

    jobs:
      build-ml-example-project-databricks-image:
        uses: ./.github/workflows/cd_docker_image_template.yml
        with:
          working-directory: projects/ml-example-project
          registry: ${{ vars.CONTAINER_REGISTRY }}
          image-name: ml-example-project-databricks
          dockerfile: docker/Dockerfile.databricks
          tag: dev-latest
        secrets: inherit

      deploy-to-dev:
        uses: ./.github/workflows/cd_dab_template.yml
        with:
          working-directory: projects/ml-example-project
          target-env: Development

          # Setting the docker image which is needed for python projects
          extra-args: '--var="docker_image_url=${{ vars.CONTAINER_REGISTRY }}/ml-example-project-databricks:dev-latest"'
        secrets: inherit
