name: Deploy ml-feature-store

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ml_feature_store_deploy.yml'
      - 'projects/ml-feature-store/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-ml-feature-store-databricks-image:
    uses: ./.github/workflows/cd_docker_image_template.yml
    with:
      working-directory: projects/ml-feature-store
      registry: ${{ vars.CONTAINER_REGISTRY }}
      image-name: ml-feature-store-databricks
      dockerfile: docker/Dockerfile.databricks
      tag: "main-latest"
      push-sha: true
    secrets: inherit

  deploy-ml-feature-store:
    strategy:
      matrix:
        target: [Test, Production]
      max-parallel: 1
      fail-fast: true
    needs: build-ml-feature-store-databricks-image
    uses: ./.github/workflows/cd_dab_template.yml
    with:
      working-directory: projects/ml-feature-store
      target-env: ${{matrix.target}}
      should-change-target: true

      # Setting the docker image which is needed for python projects
      extra-args: '--var="docker_image_url=${{ vars.CONTAINER_REGISTRY }}/ml-feature-store-databricks:${{ github.sha }}" --var="mode=production"'
    secrets: inherit
