---
name: Reusable Python library CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
      install-packages:
        description: "Space seperated list of packages to install using apt-get."
        default: ""
        type: string
      # To avoid being billed 360 minutes if a step does not terminate
      # (we've seen the setup-python step below do so!)
      ci-timeout:
        description: "The timeout of the ci job. Default is 25min"
        default: 25
        type: number

jobs:
  local-ci-py-template:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: '3.11'
          cache: "poetry"
          cache-dependency-path: |
            poetry.lock
            ${{ inputs.working-directory }}/poetry.lock

      - name: Install Python packages
        run: poetry install

      - name: Install extra packages
        if: ${{ inputs.install-packages != ''}}
        run: |
          sudo apt-get install -y ${{ inputs.install-packages }}

      - name: Typecheck
        run: |
          poetry run ruff .

      - name: Test
        run: |
          poetry run pytest -rav .  # Assume that tests are in folder "tests/"
