name: Deploy Recipe Tagging
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/recipe_tagging_deploy.yaml'
      - 'projects/recipe-tagging/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-recipe-tagging-databricks-image:
    uses: ./.github/workflows/cd_docker_image_template.yml
    with:
      working-directory: projects/recipe-tagging
      registry: ${{ vars.CONTAINER_REGISTRY }}
      image-name: recipe-tagging-databricks
      dockerfile: docker/Dockerfile.databricks
      tag: ${{ github.sha }}
    secrets: inherit

  deploy-recipe-tagging:
    strategy:
      matrix:
        target: [Test, Production]
      max-parallel: 1
      fail-fast: true
    needs: build-recipe-tagging-databricks-image
    uses: ./.github/workflows/cd_dab_template.yml
    with:
      working-directory: projects/recipe-tagging
      target-env: ${{matrix.target}}
      docker-image-name: recipe-tagging-databricks
      docker-image-tag: ${{ github.sha }}
      # Setting the docker image which is needed for python projects
      extra-args: '--var="mode=production"'
      should-change-target: true
    secrets: inherit
