name: review-screener deploy
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/review-screener_deploy.yaml'
      - 'projects/review-screener/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-review-screener-image:
    uses: ./.github/workflows/cd_docker_image_template.yml
    with:
      working-directory: projects/review-screener
      registry: ${{ vars.CONTAINER_REGISTRY }}
      image-name: review-screener
      dockerfile: docker/Dockerfile.databricks
      tag: "main-latest"
      push-sha: true
    secrets: inherit

  deploy-review-screener:
    strategy:
      matrix:
        target: [Test, Production]
      max-parallel: 1
      fail-fast: true
    needs: build-review-screener-image
    uses: ./.github/workflows/cd_dab_template.yml
    with:
      working-directory: projects/review-screener
      target-env: ${{matrix.target}}
      should-change-target: true
      # Setting the docker image which is needed for python projects
      extra-args: --var="docker_image_url=${{ vars.CONTAINER_REGISTRY }}/review-screener:${{ github.sha }}" --var="mode=production"
    secrets: inherit
