resources:
  jobs:
    attribute-scoring-train:
      name: attribute-scoring-train-${bundle.target}
      permissions:
        - group_name: data-scientists
          level: CAN_MANAGE_RUN

      job_clusters:
        - job_cluster_key: attribute-scoring-train
          new_cluster:
            num_workers: 1
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_DS4_v2
            custom_tags:
              user: "Data scientists"
              tool: "Attribute scoring"
              env: ${bundle.target}
              managed_by: "manually"
            docker_image:
              url: "${var.docker_image_url}"
              basic_auth:
                username: "{{secrets/auth_common/docker-registry-username}}"
                password: "{{secrets/auth_common/docker-registry-password}}"

      email_notifications:
        on_failure:
          - agathe.raaum@cheffelo.com
        on_success:
          - agathe.raaum@cheffelo.com

      parameters:
        - name: env
          default: "${var.environment}"
        - name: company
          default: "AMK"
        - name: target
          default: "has_chefs_favorite_taxonomy"
        - name: alias
          default: "challenger"

      tasks:
        - task_key: train-attribute-scoring
          job_cluster_key: attribute-scoring-train
          spark_python_task:
            python_file: 1_model_train.py
            parameters:
              - "--env"
              - "{{job.parameters.env}}"
              - "--company"
              - "{{job.parameters.company}}"
              - "--target"
              - "{{job.parameters.target}}"
              - "--alias"
              - "{{job.parameters.alias}}"

        - task_key: slack-notification-success
          depends_on:
            - task_key: train-attribute-scoring
          run_if: ALL_SUCCESS
          run_job_task:
            job_id: ${var.slack_notification_job_id}
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              header_message: ""
              body_message: ✅ Attribute scoring training successful!
              is_error: false

        - task_key: slack-notification-failure
          depends_on:
            - task_key: train-attribute-scoring
          run_if: ALL_FAILED
          run_job_task:
            job_id: ${var.slack_notification_job_id} #Reads from the variable defined in the databricks.yml file
            job_parameters:
              environment: ${bundle.target} #Reads from the target environment as defined in the databricks.yml file
              header_message: ❌ Attribute scoring training failed!
              body_message: Check databricks log for more details...
              is_error: true
              relevant_people: agathe
